-- INSERCIONES

---------
--ROLES--
---------
INSERT INTO ROLES (ID_ROL, NOMBRE) VALUES 
(NEXT VALUE FOR Seq_Roles, N'ADMINISTRADOR'), 
(NEXT VALUE FOR Seq_Roles, N'AGRICULTOR'), 
(NEXT VALUE FOR Seq_Roles, N'CLIENTE');

---------------
--CATEGORIAS--
---------------
INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE, DESCRIPCION) VALUES 
(NEXT VALUE FOR Seq_Categorias, N'Frutas y Cítricos', N'Fruta de temporada invernal y cítricos frescos.'),
(NEXT VALUE FOR Seq_Categorias, N'Verduras y Hortalizas', N'Hortalizas de hoja, raíces y bulbos.'),
(NEXT VALUE FOR Seq_Categorias, N'Legumbres y Tubérculos', N'Patatas, ajos, cebollas y legumbres secas.'),
(NEXT VALUE FOR Seq_Categorias, N'Frutos Secos', N'Almendras, nueces y castañas.');

------------
--USUARIOS--
------------
INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, APELLIDOS, EMAIL, CONTRASENA, IMAGEN, TELEFONO, ID_ROL) VALUES 
--Contraseña: AdminSazon
(NEXT VALUE FOR Seq_Usuarios, N'Admin', N'Sistema', N'admin@sazon.com', N'$2a$11$Yu8ixtbcUZWfXiUQXeDfl.D5hBVVG/xn/G3ZcHOw.CXdZhoUlqjQe', N'usuario-generico.png', N'600000000', 1),
--Contraseña: ClienteSazon
(NEXT VALUE FOR Seq_Usuarios, N'Carlos', N'Mora', N'carlos.mora@email.com', N'$2a$11$4z9dKq6L10owAh2eCn9AOejARH1mimNTTZeruDhb5tZDQXSkfWBPK', N'usuario-generico.png', N'639482715', 3),
(NEXT VALUE FOR Seq_Usuarios, N'Laura', N'Torres', N'laura.torres@email.com', N'$2a$11$4z9dKq6L10owAh2eCn9AOejARH1mimNTTZeruDhb5tZDQXSkfWBPK', N'usuario-generico.png', N'612554390', 3),
(NEXT VALUE FOR Seq_Usuarios, N'Pablo', N'Ruiz', N'pablo.ruiz@email.com', N'$2a$11$4z9dKq6L10owAh2eCn9AOejARH1mimNTTZeruDhb5tZDQXSkfWBPK', N'usuario-generico.png', N'677321098', 3),
(NEXT VALUE FOR Seq_Usuarios, N'Cristina', N'Díaz', N'cristina.diaz@email.com', N'$2a$11$4z9dKq6L10owAh2eCn9AOejARH1mimNTTZeruDhb5tZDQXSkfWBPK', N'usuario-generico.png', N'645221187', 3),
(NEXT VALUE FOR Seq_Usuarios, N'Miguel', N'Blanco', N'miguel.blanco@email.com', N'$2a$11$4z9dKq6L10owAh2eCn9AOejARH1mimNTTZeruDhb5tZDQXSkfWBPK', N'usuario-generico.png', N'601994432', 3),
(NEXT VALUE FOR Seq_Usuarios, N'Ángela', N'Fuentes', N'angela.fuentes@email.com', N'$2a$11$4z9dKq6L10owAh2eCn9AOejARH1mimNTTZeruDhb5tZDQXSkfWBPK', N'usuario-generico.png', N'654223399', 3),
(NEXT VALUE FOR Seq_Usuarios, N'Luis', N'Gómez', N'luis.gomez@email.com', N'$2a$11$4z9dKq6L10owAh2eCn9AOejARH1mimNTTZeruDhb5tZDQXSkfWBPK', N'usuario-generico.png', N'690112288', 3),
(NEXT VALUE FOR Seq_Usuarios, N'Sandra', N'Heredia', N'sandra.heredia@email.com', N'$2a$11$4z9dKq6L10owAh2eCn9AOejARH1mimNTTZeruDhb5tZDQXSkfWBPK', N'usuario-generico.png', N'633445566', 3),
(NEXT VALUE FOR Seq_Usuarios, N'Raúl', N'Vegas', N'raul.vegas@email.com', N'$2a$11$4z9dKq6L10owAh2eCn9AOejARH1mimNTTZeruDhb5tZDQXSkfWBPK', N'usuario-generico.png', N'622998877', 3),
(NEXT VALUE FOR Seq_Usuarios, N'Sofía', N'Castillo', N'sofia.castillo@email.com', N'$2a$11$4z9dKq6L10owAh2eCn9AOejARH1mimNTTZeruDhb5tZDQXSkfWBPK', N'usuario-generico.png', N'678554433', 3),
(NEXT VALUE FOR Seq_Usuarios, N'Hugo', N'Santos', N'hugo.santos@email.com', N'$2a$11$4z9dKq6L10owAh2eCn9AOejARH1mimNTTZeruDhb5tZDQXSkfWBPK', N'usuario-generico.png', N'611223344', 3),
(NEXT VALUE FOR Seq_Usuarios, N'Esther', N'Navarro', N'esther.navarro@email.com', N'$2a$11$4z9dKq6L10owAh2eCn9AOejARH1mimNTTZeruDhb5tZDQXSkfWBPK', N'usuario-generico.png', N'644332211', 3),
(NEXT VALUE FOR Seq_Usuarios, N'Mario', N'Reyes', N'mario.reyes@email.com', N'$2a$11$4z9dKq6L10owAh2eCn9AOejARH1mimNTTZeruDhb5tZDQXSkfWBPK', N'usuario-generico.png', N'699887766', 3),
(NEXT VALUE FOR Seq_Usuarios, N'Alba', N'Guerrero', N'alba.guerrero@email.com', N'$2a$11$4z9dKq6L10owAh2eCn9AOejARH1mimNTTZeruDhb5tZDQXSkfWBPK', N'usuario-generico.png', N'655443322', 3),
(NEXT VALUE FOR Seq_Usuarios, N'David', N'Molina', N'david.molina@email.com', N'$2a$11$4z9dKq6L10owAh2eCn9AOejARH1mimNTTZeruDhb5tZDQXSkfWBPK', N'usuario-generico.png', N'621110099', 3),
--Contraseña: AgricultorSazon
(NEXT VALUE FOR Seq_Usuarios, N'Paco', N'García', N'paco.garcia@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'629564629', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Roberto', N'Sánchez', N'roberto.sanchez@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'618223344', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Elena', N'Martínez', N'elena.martinez@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'647338811', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Marta', N'Roca', N'marta.roca@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'605992288', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Diego', N'Sanz', N'diego.sanz@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'639441122', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Sonia', N'León', N'sonia.leon@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'677553311', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Raquel', N'Díaz', N'raquel.diaz@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'641220099', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Adrián', N'Pino', N'adrian.pino@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'654887733', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Beatriz', N'Luna', N'beatriz.luna@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'661992244', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Antonio', N'Ruiz', N'antonio.ruiz@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'620337711', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Jordi', N'Pujol', N'jordi.puyol@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'693441188', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Montserrat', N'Vila', N'montse.vila@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'604552211', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Oriol', N'Roura', N'oriol.roura@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'617993344', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Arantxa', N'Sánchez', N'arantxa.sanchez@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'628115566', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Pol', N'García', N'pol.garcia@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'639228899', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Miquel', N'Serra', N'miquel.serra@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'641331100', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Carla', N'Soler', N'carla.soler@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'652443322', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Ferran', N'Llopis', N'ferran.llopis@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'663554433', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Mireia', N'Belda', N'mireia.belda@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'674665544', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Joan', N'Rico', N'joan.rico@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'685776655', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Curro', N'Reyes', N'curro.reyes@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'696887766', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Macarena', N'Gil', N'macarena.gil@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'607118877', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Rocío', N'Lara', N'rocio.lara@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'618229988', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Manuel', N'Soria', N'manuel.soria@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'629330099', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Lola', N'martinez', N'lola.martinez@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'630441100', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Pepe', N'Vila', N'pepe.vila@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'641552211', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Carmen', N'Díaz', N'carmen.diaz@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'652663322', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Juan', N'Cano', N'juan.cano@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'663774433', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Fran', N'Luna', N'fran.luna@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'674885544', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Jose', N'Ramos', N'jose.ramos@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'685996655', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Vicente', N'Ferrer', N'vicente.ferrer@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'609112233', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Amparo', N'Pla', N'amparo.pla@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'620223344', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Neus', N'Sanz', N'neus.sanz@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'631334455', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Pau', N'Marí', N'pau.mari@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'642445566', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Ximo', N'Puig', N'ximo.puig@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'653556677', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Susi', N'Díaz', N'susi.diaz@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'664667788', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Jaime', N'Miralles', N'jaime.miralles@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'675778899', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Quico', N'López', N'quico.lopez@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'686889900', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Pascual', N'Cano', N'pascual.cano@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'697990011', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Encarna', N'Molina', N'encarna.molina@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'608001122', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Tomas', N'Zamora', N'tomas.zamora@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'638112200', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Sagra', N'Toledo', N'sagra.toledo@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'641223311', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Rodrigo', N'Díaz', N'rodri.diaz@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'654334422', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Casandra', N'Gil', N'casandra.gil@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'667445533', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Paola', N'León', N'paola.leon@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'670556644', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Velasco', N'Mendoza', N'velasco.mendoza@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'683667755', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Eugenia', N'Ruiz', N'eugenia.ruiz@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y3', N'usuario-generico.png', N'696778866', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Mencia', N'Alba', N'mencia.alba@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'609889977', 2),
(NEXT VALUE FOR Seq_Usuarios, N'Beatriz', N'Sanz', N'beatriz.sanz@email.com', N'$2a$11$tGVgLtqDJ.Fovsj16BhXauEhGag6lHTQ4LlcVPHpy4fXcH3euNs4y', N'usuario-generico.png', N'612990088', 2);

---------------
--DIRECCIONES--
---------------
INSERT INTO DIRECCIONES (ID_DIRECCION, NOMBRE_ETIQUETA, CALLE_NUMERO, CODIGO_POSTAL, MUNICIPIO, PROVINCIA, LATITUD, LONGITUD, ES_PRINCIPAL, ID_USUARIO) VALUES
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Real 10', N'28740', N'Rascafría', N'Madrid', 40.9014, -3.8755, 1, 3),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Plaza Mayor 1', N'28300', N'Aranjuez', N'Madrid', 40.0333, -3.6000, 1, 4),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle de la Luna 4', N'28801', N'Alcalá de Henares', N'Madrid', 40.4819, -3.3636, 1, 5),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Avenida de la Constitución 12', N'28210', N'Robledo de Chavela', N'Madrid', 40.5011, -4.2389, 1, 6),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Goya 25', N'28001', N'Madrid', N'Madrid', 40.4250, -3.6833, 1, 7),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle de la Estación 2', N'28400', N'Collado Villalba', N'Madrid', 40.6333, -3.9833, 1, 8),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle del Pez 15', N'28004', N'Madrid', N'Madrid', 40.4233, -3.7055, 1, 9),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle de Madrid 50', N'28901', N'Getafe', N'Madrid', 40.3083, -3.7333, 1, 10),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle de Alcalá 15', N'28014', N'Madrid', N'Madrid', 40.4189, -3.6995, 1, 2),
(NEXT VALUE FOR Seq_Direcciones, N'Trabajo', N'Paseo de la Castellana 200', N'28046', N'Madrid', N'Madrid', 40.4589, -3.6922, 0, 2),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Serrano 40', N'28001', N'Madrid', N'Madrid', 40.4255, -3.6871, 1, 14),
(NEXT VALUE FOR Seq_Direcciones, N'Trabajo', N'Calle Jorge Juan 12', N'28001', N'Madrid', N'Madrid', 40.4240, -3.6850, 0, 14),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Segovia 10', N'28005', N'Madrid', N'Madrid', 40.4133, -3.7150, 1, 11),
(NEXT VALUE FOR Seq_Direcciones, N'Trabajo', N'Alcobendas Business Hub', N'28108', N'Alcobendas', N'Madrid', 40.5475, -3.6420, 0, 11),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Avenida de España 40', N'28220', N'Majadahonda', N'Madrid', 40.4730, -3.8710, 1, 13),
(NEXT VALUE FOR Seq_Direcciones, N'Trabajo', N'Calle Orense 15', N'28020', N'Madrid', N'Madrid', 40.4490, -3.6950, 0, 13),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle de la Victoria 3', N'28821', N'Coslada', N'Madrid', 40.4258, -3.5650, 1, 12),
(NEXT VALUE FOR Seq_Direcciones, N'Trabajo', N'Paseo del Prado 1', N'28014', N'Madrid', N'Madrid', 40.4140, -3.6940, 0, 12),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Princesa 20', N'28008', N'Madrid', N'Madrid', 40.4280, -3.7140, 1, 16),
(NEXT VALUE FOR Seq_Direcciones, N'Trabajo', N'Gran Vía 1', N'28013', N'Madrid', N'Madrid', 40.4190, -3.6990, 0, 16),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Pintor Rosales 2', N'28008', N'Madrid', N'Madrid', 40.4290, -3.7220, 1, 15),
(NEXT VALUE FOR Seq_Direcciones, N'Trabajo', N'Polígono Fuenlabrada', N'28946', N'Fuenlabrada', N'Madrid', 40.2840, -3.7940, 0, 15),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle de la Fuente 2', N'28350', N'Ciempozuelos', N'Madrid', 40.1580, -3.6160, 1, 17),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Mayor 10', N'28750', N'San Agustín del Guadalix', N'Madrid', 40.6775, -3.6150, 1, 18),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Nueva 4', N'28210', N'Valdemorillo', N'Madrid', 40.4470, -3.9930, 1, 19),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle de la Amargura 5', N'28320', N'Pinto', N'Madrid', 40.2410, -3.6980, 1, 20),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Juan de la Cierva 1', N'28500', N'Arganda del Rey', N'Madrid', 40.3000, -3.4330, 1, 21),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Plaza del Pueblo 2', N'28720', N'Bustarviejo', N'Madrid', 40.8580, -3.7090, 1, 22),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle de la Iglesia 1', N'28140', N'Fuente el Saz', N'Madrid', 40.6330, -3.5110, 1, 23),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Real 100', N'28970', N'Humanes', N'Madrid', 40.2520, -3.8270, 1, 24),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Arriba 22', N'28411', N'Moralzarzal', N'Madrid', 40.6750, -3.9710, 1, 25),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Avenida de Madrid 45', N'28850', N'Torrejón de Ardoz', N'Madrid', 40.4560, -3.4720, 1, 26),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle de la Huerta 9', N'28341', N'Valdemoro', N'Madrid', 40.1900, -3.6770, 1, 27),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Campo 30', N'28600', N'Navalcarnero', N'Madrid', 40.2880, -4.0120, 1, 28),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle del Río 12', N'28430', N'Alpedrete', N'Madrid', 40.6600, -4.0200, 1, 29),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Enmedio 5', N'28814', N'Daganzo', N'Madrid', 40.5400, -3.4500, 1, 30),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle de la Paz 8', N'28911', N'Leganés', N'Madrid', 40.3200, -3.7600, 1, 31),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle San Isidro 3', N'28691', N'Villanueva de la Cañada', N'Madrid', 40.4400, -3.9900, 1, 32),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle del Sol 21', N'28806', N'Alcalá de Henares', N'Madrid', 40.4900, -3.3500, 1, 33),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Estación 4', N'28231', N'Las Rozas', N'Madrid', 40.4900, -3.8700, 1, 34),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle del Prado 6', N'28710', N'El Molar', N'Madrid', 40.7300, -3.5800, 1, 35),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Mayor 50', N'28670', N'Villaviciosa de Odón', N'Madrid', 40.3500, -3.9000, 1, 36),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle de la Ermita 2', N'28390', N'Belmonte de Tajo', N'Madrid', 40.1300, -3.3400, 1, 37),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Pintor 1', N'28944', N'Fuenlabrada', N'Madrid', 40.2900, -3.7900, 1, 38),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Avenida del Guadarrama 4', N'28440', N'Guadarrama', N'Madrid', 40.6700, -4.0800, 1, 39),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Alta 15', N'28180', N'Torrelaguna', N'Madrid', 40.8200, -3.5300, 1, 40),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle del Pozo 3', N'28510', N'Campo Real', N'Madrid', 40.3300, -3.3800, 1, 41),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Estrecha 9', N'28359', N'Titulcia', N'Madrid', 40.1300, -3.5500, 1, 42),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle la Vía 5', N'28770', N'Colmenar Viejo', N'Madrid', 40.6500, -3.7600, 1, 43),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle del Pino 11', N'28594', N'Villarejo de Salvanés', N'Madrid', 40.1600, -3.2700, 1, 44),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Soria 2', N'28224', N'Pozuelo', N'Madrid', 40.4300, -3.7800, 1, 45),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Castillo 7', N'28607', N'El Álamo', N'Madrid', 40.2300, -3.9900, 1, 46),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle del Norte 1', N'28792', N'Miraflores de la Sierra', N'Madrid', 40.8100, -3.7600, 1, 47),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle de la Peña 3', N'28410', N'Manzanares el Real', N'Madrid', 40.7200, -3.8600, 1, 48),
(NEXT VALUE FOR Seq_Direcciones, N'Casa', N'Calle Mayor 90', N'28931', N'Móstoles', N'Madrid', 40.3200, -3.8600, 1, 49);

-----------
-- FINCAS--
-----------
INSERT INTO FINCAS (ID_FINCA, NOMBRE, DIRECCION, MUNICIPIO, PROVINCIA, LATITUD, LONGITUD, ID_USUARIO) VALUES
(NEXT VALUE FOR Seq_Fincas, N'Huerta del Tajo', N'Camino de la Vega, Parcela 12', N'Aranjuez', N'Madrid', 40.0450, -3.5820, 17),
(NEXT VALUE FOR Seq_Fincas, N'El Olivar de Paco', N'Polígono 4, Recinto 5', N'Titulcia', N'Madrid', 40.1380, -3.5510, 17),
(NEXT VALUE FOR Seq_Fincas, N'Finca El Jarama', N'Vía Pecuaria km 2.5', N'Algete', N'Madrid', 40.6120, -3.4980, 18),
(NEXT VALUE FOR Seq_Fincas, N'Huerta Norte', N'Camino de las Huelgas s/n', N'San Sebastián de los Reyes', N'Madrid', 40.5850, -3.5710, 18),
(NEXT VALUE FOR Seq_Fincas, N'Valle del Guadarrama', N'Cañada Real Segoviana, Parcela 88', N'Brunete', N'Madrid', 40.3990, -3.9850, 19),
(NEXT VALUE FOR Seq_Fincas, N'Finca La Pizarra', N'Camino vecinal de Quijorna', N'Quijorna', N'Madrid', 40.4280, -4.0550, 19),
(NEXT VALUE FOR Seq_Fincas, N'Vegas del Sur', N'Polígono Industrial La Estación, trasera', N'Pinto', N'Madrid', 40.2450, -3.7120, 20),
(NEXT VALUE FOR Seq_Fincas, N'Huerta La Atalaya', N'Camino Bajo de Valdemoro', N'Valdemoro', N'Madrid', 40.2010, -3.6620, 20),
(NEXT VALUE FOR Seq_Fincas, N'Campiña del Henares', N'Camino de los Cocheros s/n', N'Loeches', N'Madrid', 40.3850, -3.4120, 21),
(NEXT VALUE FOR Seq_Fincas, N'Finca El Jaral', N'Carretera M-300 km 12', N'Arganda del Rey', N'Madrid', 40.3120, -3.4550, 21),
(NEXT VALUE FOR Seq_Fincas, N'Prados de la Sierra', N'Camino de la Ermita, Parcela 10', N'Miraflores de la Sierra', N'Madrid', 40.8150, -3.7710, 22),
(NEXT VALUE FOR Seq_Fincas, N'Huerta del Valle', N'Paraje La Viña s/n', N'Canencia', N'Madrid', 40.9020, -3.7410, 22),
(NEXT VALUE FOR Seq_Fincas, N'Finca La Campiña', N'Camino de Algete km 1', N'Fuente el Saz', N'Madrid', 40.6410, -3.5050, 23),
(NEXT VALUE FOR Seq_Fincas, N'Vegas de Valdeolmos', N'Polígono 2, Parcela 40', N'Valdeolmos', N'Madrid', 40.6350, -3.4610, 23),
(NEXT VALUE FOR Seq_Fincas, N'El Huerto de Adrián', N'Vereda de las Vacas', N'Griñón', N'Madrid', 40.2180, -3.8450, 24),
(NEXT VALUE FOR Seq_Fincas, N'Finca Los Pinos', N'Camino Real de Fuenlabrada', N'Humanes', N'Madrid', 40.2580, -3.8120, 24),
(NEXT VALUE FOR Seq_Fincas, N'Sierra de Guadarrama', N'Camino de la Pedriza s/n', N'Manzanares el Real', N'Madrid', 40.7280, -3.8710, 25),
(NEXT VALUE FOR Seq_Fincas, N'Huerta del Berrocal', N'Paraje Los Llanos', N'Cerceda', N'Madrid', 40.6950, -3.9210, 25),
(NEXT VALUE FOR Seq_Fincas, N'Finca El Henares', N'Camino de la Ribera, Parcela 5', N'San Fernando de Henares', N'Madrid', 40.4520, -3.5150, 26),
(NEXT VALUE FOR Seq_Fincas, N'Huerta El Soto', N'Polígono 12, Recinto 2', N'Torrejón de Ardoz', N'Madrid', 40.4680, -3.4520, 26),
(NEXT VALUE FOR Seq_Fincas, N'Vegas del Tajuña', N'Camino de San Martín de la Vega', N'San Martín de la Vega', N'Madrid', 40.2150, -3.5710, 27),
(NEXT VALUE FOR Seq_Fincas, N'Finca La Garena', N'Vereda del Sur s/n', N'Valdemoro', N'Madrid', 40.1820, -3.6920, 27),
(NEXT VALUE FOR Seq_Fincas, N'El Viñedo Viejo', N'Camino de Sevilla la Nueva', N'Sevilla la Nueva', N'Madrid', 40.3450, -4.0120, 28),
(NEXT VALUE FOR Seq_Fincas, N'Huerta de Navalcarnero', N'Polígono Ganadero, Parcela 9', N'Navalcarnero', N'Madrid', 40.2920, -4.0320, 28),
(NEXT VALUE FOR Seq_Fincas, N'Sierra del Castillejo', N'Camino del Monte s/n', N'Guadarrama', N'Madrid', 40.6750, -4.0720, 29),
(NEXT VALUE FOR Seq_Fincas, N'Huerta de Alpedrete', N'Vereda de los Molinos', N'Alpedrete', N'Madrid', 40.6650, -4.0350, 29),
(NEXT VALUE FOR Seq_Fincas, N'Campiña de Daganzo', N'Camino de Ajalvir km 2', N'Ajalvir', N'Madrid', 40.5310, -3.4750, 30),
(NEXT VALUE FOR Seq_Fincas, N'Finca La Solana', N'Polígono 5, Parcela 12', N'Daganzo de Arriba', N'Madrid', 40.5480, -3.4420, 30),
(NEXT VALUE FOR Seq_Fincas, N'Huerta Sur Leganés', N'Camino de Polvoranca', N'Leganés', N'Madrid', 40.3250, -3.7820, 31),
(NEXT VALUE FOR Seq_Fincas, N'Finca La Cañada', N'Paraje El Pinar s/n', N'Villanueva de la Cañada', N'Madrid', 40.4510, -4.0120, 32),
(NEXT VALUE FOR Seq_Fincas, N'Vegas de Alcalá', N'Camino del Juncal', N'Alcalá de Henares', N'Madrid', 40.4950, -3.3420, 33),
(NEXT VALUE FOR Seq_Fincas, N'Sierra de Las Rozas', N'Dehesa de Navalcarbón', N'Las Rozas', N'Madrid', 40.5010, -3.8920, 34),
(NEXT VALUE FOR Seq_Fincas, N'Finca El Molar', N'Camino de la Sierra km 1', N'El Molar', N'Madrid', 40.7350, -3.5720, 35),
(NEXT VALUE FOR Seq_Fincas, N'Huerta del Odón', N'Paraje Campodón', N'Villaviciosa de Odón', N'Madrid', 40.3420, -3.9220, 36),
(NEXT VALUE FOR Seq_Fincas, N'Vegas de Belmonte', N'Camino de Villarejo', N'Belmonte de Tajo', N'Madrid', 40.1250, -3.3220, 37),
(NEXT VALUE FOR Seq_Fincas, N'Finca Fuenlabrada', N'Polígono Industrial Cantueña, trasera', N'Fuenlabrada', N'Madrid', 40.2750, -3.7820, 38),
(NEXT VALUE FOR Seq_Fincas, N'Montes de Guadarrama', N'Valle de la Jarosa', N'Guadarrama', N'Madrid', 40.6810, -4.1020, 39),
(NEXT VALUE FOR Seq_Fincas, N'Huerta de Torrelaguna', N'Canal de Isabel II, lateral', N'Torrelaguna', N'Madrid', 40.8250, -3.5220, 40),
(NEXT VALUE FOR Seq_Fincas, N'Finca Campo Real', N'Camino de las Aceitunas', N'Campo Real', N'Madrid', 40.3350, -3.3720, 41),
(NEXT VALUE FOR Seq_Fincas, N'Vegas de Titulcia', N'Paraje El Raso', N'Titulcia', N'Madrid', 40.1350, -3.5620, 42),
(NEXT VALUE FOR Seq_Fincas, N'Dehesa de Colmenar', N'Camino de la Ermita Remedios', N'Colmenar Viejo', N'Madrid', 40.6650, -3.7520, 43),
(NEXT VALUE FOR Seq_Fincas, N'Finca El Castillo', N'Carretera de Chinchón km 5', N'Villarejo de Salvanés', N'Madrid', 40.1550, -3.2820, 44),
(NEXT VALUE FOR Seq_Fincas, N'Huerta de Pozuelo', N'Paraje Arroyo Meaques', N'Pozuelo de Alarcón', N'Madrid', 40.4250, -3.7920, 45),
(NEXT VALUE FOR Seq_Fincas, N'Vegas del Álamo', N'Camino de Casarrubios', N'El Álamo', N'Madrid', 40.2250, -4.0020, 46),
(NEXT VALUE FOR Seq_Fincas, N'Sierra de Miraflores', N'Camino del Puerto s/n', N'Miraflores de la Sierra', N'Madrid', 40.8210, -3.7520, 47),
(NEXT VALUE FOR Seq_Fincas, N'Huerta del Real', N'Paraje del Embalse Santillana', N'Manzanares el Real', N'Madrid', 40.7150, -3.8520, 48),
(NEXT VALUE FOR Seq_Fincas, N'Finca Móstoles Sur', N'Polígono Las Nieves', N'Móstoles', N'Madrid', 40.3150, -3.8720, 49),
(NEXT VALUE FOR Seq_Fincas, N'Vegas de Getafe', N'Camino del Cerro de los Ángeles', N'Getafe', N'Madrid', 40.3020, -3.7020, 50),
(NEXT VALUE FOR Seq_Fincas, N'Huerta de Parla', N'Paraje Las Fuentecillas', N'Parla', N'Madrid', 40.2280, -3.7620, 51),
(NEXT VALUE FOR Seq_Fincas, N'Finca El Tajuña', N'Camino de Morata', N'Perales de Tajuña', N'Madrid', 40.2310, -3.3520, 52),
(NEXT VALUE FOR Seq_Fincas, N'Sierra de Galapagar', N'Camino de la Navata', N'Galapagar', N'Madrid', 40.5750, -4.0020, 53),
(NEXT VALUE FOR Seq_Fincas, N'Vegas de Ciempozuelos', N'Camino del Río', N'Ciempozuelos', N'Madrid', 40.1650, -3.6020, 54),
(NEXT VALUE FOR Seq_Fincas, N'Finca San Martín', N'Carretera M-506 km 15', N'San Martín de la Vega', N'Madrid', 40.2050, -3.5820, 55),
(NEXT VALUE FOR Seq_Fincas, N'Huerta de Valdemoro', N'Camino del Espartal', N'Valdemoro', N'Madrid', 40.1850, -3.6620, 56),
(NEXT VALUE FOR Seq_Fincas, N'Sierra de Guadarrama II', N'Puerto de Navacerrada bajo', N'Cercedilla', N'Madrid', 40.7350, -4.0620, 57),
(NEXT VALUE FOR Seq_Fincas, N'Finca del Henares II', N'Polígono Industrial de Alcalá', N'Alcalá de Henares', N'Madrid', 40.4850, -3.3320, 58),
(NEXT VALUE FOR Seq_Fincas, N'Huerta de Chinchón', N'Vegas del Tajuña sector B', N'Chinchón', N'Madrid', 40.1450, -3.4220, 59),
(NEXT VALUE FOR Seq_Fincas, N'Finca Boadilla', N'Monte de Boadilla Parcela 1', N'Boadilla del Monte', N'Madrid', 40.4050, -3.8820, 60),
(NEXT VALUE FOR Seq_Fincas, N'Sierra del Hoyo', N'Camino de la Berzosa', N'Hoyo de Manzanares', N'Madrid', 40.6250, -3.9020, 61),
(NEXT VALUE FOR Seq_Fincas, N'Vegas del Jarama', N'Camino del Aeropuerto lateral', N'Paracuellos de Jarama', N'Madrid', 40.5150, -3.5220, 62),
(NEXT VALUE FOR Seq_Fincas, N'Finca de Brunete', N'Camino de Boadilla s/n', N'Brunete', N'Madrid', 40.4150, -3.9420, 63),
(NEXT VALUE FOR Seq_Fincas, N'Huerta de Cadalso', N'Paraje Los Viñedos', N'Cadalso de los Vidrios', N'Madrid', 40.3050, -4.4420, 64),
(NEXT VALUE FOR Seq_Fincas, N'Sierra de Pelayos', N'Pantano de San Juan sector norte', N'Pelayos de la Presa', N'Madrid', 40.3550, -4.3320, 65);

-----------------
--SUBCATEGORIAS--
-----------------
INSERT INTO SUBCATEGORIAS (ID_SUBCATEGORIA, NOMBRE, IMAGEN, DESCRIPCION, ID_CATEGORIA) VALUES 
(NEXT VALUE FOR Seq_Subcategorias, N'Cítricos', N'citricos.png', N'Naranjas, limones, mandarinas, limas y variedades similares de temporada.', 1),
(NEXT VALUE FOR Seq_Subcategorias, N'Fruta de Hueso', N'fruta-hueso.png', N'Melocotones, nectarinas, paraguayos, albaricoques, ciruelas y cerezas.', 1),
(NEXT VALUE FOR Seq_Subcategorias, N'Fruta de Pepita', N'fruta-con-pepita.png', N'Todas las variedades de manzanas (Golden, Fuji, Reineta) y peras (Conferencia, Ercolina).', 1),
(NEXT VALUE FOR Seq_Subcategorias, N'Fruta Exótica', N'fruta-exotica.png', N'Kiwi, plátano, piña, granada, aguacate, chirimoya y mango.', 1),
(NEXT VALUE FOR Seq_Subcategorias, N'Tomate', N'tomate.png', N'Tomate en rama, rosa, cherry, kumato, de Montserrat y otras variedades locales.', 2),
(NEXT VALUE FOR Seq_Subcategorias, N'Verdura Ensalada', N'verduras-ensalada.png', N'Lechugas (Romana, Batavia), canónigos, rúcula, escarola y brotes tiernos.', 2),
(NEXT VALUE FOR Seq_Subcategorias, N'Verdura de Hoja', N'verduras-hoja.png', N'Acelgas, espinacas, berzas, grelos y navizas.', 2),
(NEXT VALUE FOR Seq_Subcategorias, N'Col y Crucífera', N'col-y-crucifera.png', N'Brócoli, coliflor, repollo, lombarda y coles de Bruselas.', 2),
(NEXT VALUE FOR Seq_Subcategorias, N'Hortalizas Alargadas', N'hortalizas-alargadas.png', N'Calabacín, pepino y berenjenas (negra, blanca, listada).', 2),
(NEXT VALUE FOR Seq_Subcategorias, N'Alcachofa', N'alcachofa.png', N'Alcachofas frescas de temporada (Prat, Tudela, etc.).', 2),
(NEXT VALUE FOR Seq_Subcategorias, N'Pimiento', N'pimiento.png', N'Pimiento rojo, verde, italiano, de Padrón y ñoras.', 2),
(NEXT VALUE FOR Seq_Subcategorias, N'Tallos', N'tallos.png', N'Puerros, espárragos trigeros o blancos, apio e hinojo.', 2),
(NEXT VALUE FOR Seq_Subcategorias, N'Setas', N'setas.png', N'Champiñón, setas de cardo, níscalos y hongos silvestres.', 2),
(NEXT VALUE FOR Seq_Subcategorias, N'Cebolla y Bulbo', N'cebolla-y-bulbo.png', N'Cebollas, cebolletas, chalotas y calçots.', 3),
(NEXT VALUE FOR Seq_Subcategorias, N'Ajo', N'ajo.png', N'Ajo blanco, morado, negro, ajos tiernos y pasta de ajo.', 3),
(NEXT VALUE FOR Seq_Subcategorias, N'Raíz y Remolacha', N'raiz-y-remolacha.png', N'Zanahorias, rábanos, nabos, chirivía y remolacha fresca.', 3),
(NEXT VALUE FOR Seq_Subcategorias, N'Tubérculos', N'tuberculos.png', N'Todas las variedades de patatas (Kennebec, Roja, Agria), yuca y jengibre.', 3),
(NEXT VALUE FOR Seq_Subcategorias, N'Tubérculos Dulces', N'tuberculos-dulces.png', N'Boniato, batata y diversas variedades de calabazas.', 3),
(NEXT VALUE FOR Seq_Subcategorias, N'Legumbres Secas', N'legumbres-secas.png', N'Garbanzos, lentejas y alubias secas de todo tipo.', 3),
(NEXT VALUE FOR Seq_Subcategorias, N'Legumbres de Vaina', N'legumbres-vaina.png', N'Habas tiernas, guisantes y judía verde fresca.', 3),
(NEXT VALUE FOR Seq_Subcategorias, N'Frutos Secos Naturales', N'frutos-secos-naturales.png', N'Nueces, almendras, avellanas y castañas, con o sin cáscara.', 4),
(NEXT VALUE FOR Seq_Subcategorias, N'Frutos Secos Gourmet', N'frutos-secos-gourmet.png', N'Pistachos, piñones, anacardos, dátiles, higos secos y pasas.', 4),
(NEXT VALUE FOR Seq_Subcategorias, N'Melón y Sandía', N'melon-sandia.png', N'Diferentes variedades de melones y sandías de temporada.', 1),
(NEXT VALUE FOR Seq_Subcategorias, N'Frutos Rojos', N'frutos-rojos.png', N'Fresas, fresones, frambuesas, arándanos y moras.', 1),
(NEXT VALUE FOR Seq_Subcategorias, N'Fruta de Otoño', N'fruta-otono.png', N'Higos, brevas, membrillos, caquis y castañas frescas.', 1);

-------------
--PRODUCTOS--
-------------
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE, DESCRIPCION, PRECIO_UNIDAD, UNIDAD_MEDIDA, STOCK, ID_FINCA, ID_SUBCATEGORIA, ID_CATEGORIA) VALUES
(NEXT VALUE FOR Seq_Productos, N'Tomate Rosa', N'Sabor tradicional', 2.90, N'KG', 100, 1, 5, 2),
(NEXT VALUE FOR Seq_Productos, N'Lechuga Romana', N'Fresca y crujiente', 1.10, N'Unidad', 80, 1, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Espárrago Triguero', N'Manojo silvestre', 3.50, N'Manojo', 50, 1, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Pimiento Rojo', N'Carnoso para asar', 2.80, N'KG', 70, 1, 18, 2),
(NEXT VALUE FOR Seq_Productos, N'Manzana Fuji', N'Muy dulce', 1.80, N'KG', 200, 1, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Pera Ercolina', N'Jugosa y dulce', 1.95, N'KG', 150, 1, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Calabacín Fino', N'Piel tierna', 1.70, N'KG', 120, 1, 16, 2),
(NEXT VALUE FOR Seq_Productos, N'Cebolla Roja', N'Ideal ensaladas', 1.40, N'KG', 100, 1, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Garbanzo Pedrosillano', N'Grano pequeño', 3.10, N'KG', 300, 2, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Lenteja Pardina', N'No necesita remojo', 2.40, N'KG', 400, 2, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Almendra Marcona', N'Calidad extra', 9.50, N'KG', 50, 2, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Nuez con Cáscara', N'Secado natural', 4.80, N'KG', 100, 2, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Ajo Morado Cabeza', N'Sabor potente', 4.20, N'KG', 100, 2, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Patata Kennebec', N'Para todo uso', 1.00, N'KG', 500, 2, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Pistacho Tostado', N'Con sal marina', 11.00, N'KG', 40, 2, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Higo Paso', N'Dulce natural', 7.20, N'KG', 50, 2, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Brócoli Fresco', N'Ramillete verde', 1.60, N'Unidad', 100, 3, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Coliflor Blanca', N'Pieza grande', 1.85, N'Unidad', 60, 3, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Lombarda', N'Especial Madrid', 1.50, N'Unidad', 70, 3, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Espinaca Fresca', N'Hoja ancha', 1.30, N'Manojo', 80, 3, 7, 2),
(NEXT VALUE FOR Seq_Productos, N'Acelga', N'Manojo 500g', 1.10, N'Manojo', 100, 3, 7, 2),
(NEXT VALUE FOR Seq_Productos, N'Puerro Grueso', N'Para cremas', 1.45, N'Manojo', 90, 3, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Apio', N'Manojo blanco', 1.20, N'Manojo', 50, 3, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Zanahoria Dulce', N'Con rama', 1.25, N'Manojo', 110, 3, 11, 2),
(NEXT VALUE FOR Seq_Productos, N'Boniato', N'Especial asar', 1.70, N'KG', 200, 4, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Calabaza Ruperta', N'Para purés', 1.20, N'KG', 180, 4, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Patata Roja', N'Para cocer', 1.15, N'KG', 600, 4, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Naranja Navel', N'Mesa y zumo', 1.40, N'KG', 500, 4, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Limón Verna', N'Mucha vitamina C', 1.50, N'KG', 200, 4, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Mandarina', N'Fácil pelar', 1.70, N'KG', 400, 4, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Dátil Medjool', N'Premium', 14.00, N'KG', 30, 4, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Avellana Tostada', N'Sabor intenso', 8.50, N'KG', 40, 4, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Tomate Rosa de Brunete', N'Carnoso y con sabor a huerta antigua', 3.10, N'KG', 120, 5, 5, 2),
(NEXT VALUE FOR Seq_Productos, N'Lechuga Batavia', N'Hoja rizada muy tierna', 1.20, N'Unidad', 90, 5, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Cebolla Blanca', N'Dulce, ideal para ensaladas', 1.15, N'KG', 300, 5, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Ajo Morado', N'Sabor potente e intenso', 4.30, N'KG', 100, 5, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Patata Kennebec', N'Ideal para asar y cocer', 1.05, N'KG', 600, 5, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Zanahoria con Rama', N'Dulce y crujiente', 1.40, N'Manojo', 80, 5, 11, 3),
(NEXT VALUE FOR Seq_Productos, N'Manzana Golden', N'Crujiente y muy dulce', 1.70, N'KG', 200, 5, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Pera Conferencia', N'Textura granulosa exquisita', 1.85, N'KG', 150, 5, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Calabacín Verde', N'Piel fina y tierna', 1.80, N'KG', 150, 6, 16, 2),
(NEXT VALUE FOR Seq_Productos, N'Pepino Holandés', N'Sin amargor, muy refrescante', 1.60, N'KG', 100, 6, 16, 2),
(NEXT VALUE FOR Seq_Productos, N'Pimiento Rojo Morrón', N'Ideal para asar al horno', 2.90, N'KG', 70, 6, 18, 2),
(NEXT VALUE FOR Seq_Productos, N'Habas Tiernas', N'Vaina pequeña y dulce', 3.80, N'KG', 60, 6, 15, 3),
(NEXT VALUE FOR Seq_Productos, N'Guisante Fresco', N'Para desgranar en casa', 4.50, N'KG', 50, 6, 15, 3),
(NEXT VALUE FOR Seq_Productos, N'Limón Verna', N'Mucha vitamina C', 1.55, N'KG', 120, 6, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Nuez en Grano', N'Recién pelada artesanalmente', 8.50, N'KG', 40, 6, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Dátiles Naturales', N'Energía pura de invierno', 12.00, N'KG', 30, 6, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Alcachofa Tierna', N'Corazón blando y sabroso', 3.20, N'KG', 140, 7, 17, 2),
(NEXT VALUE FOR Seq_Productos, N'Puerro de Verdeo', N'Blanco y largo para caldos', 1.60, N'Manojo', 100, 7, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Brócoli en Ramillete', N'Súper alimento del sur de Madrid', 1.75, N'Unidad', 110, 7, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Coliflor Blanca', N'Pieza compacta y grande', 1.95, N'Unidad', 60, 7, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Espinaca Fresca', N'Hoja ancha lista para cocinar', 1.40, N'Manojo', 80, 7, 7, 2),
(NEXT VALUE FOR Seq_Productos, N'Repollo Liso', N'Perfecto para cocido madrileño', 1.30, N'Unidad', 70, 7, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Acelga terna', N'Manojo 500g muy fresco', 1.15, N'Manojo', 90, 7, 7, 2),
(NEXT VALUE FOR Seq_Productos, N'Remolacha con Hojas', N'Ideal para ensaladas nutritivas', 1.35, N'Manojo', 50, 7, 11, 3),
(NEXT VALUE FOR Seq_Productos, N'Champiñón de París', N'Seleccionado, blanco y firme', 3.50, N'KG', 150, 8, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Seta de Cardo', N'Carnosas y con aroma a campo', 8.90, N'KG', 40, 8, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Pasta de Ajo Natural', N'Mortero artesano 100g', 3.60, N'Unidad', 50, 8, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Lenteja de la Vega', N'Cosecha propia de secano', 2.45, N'KG', 400, 8, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Garbanzo Gordo', N'Extra tierno, piel muy fina', 3.15, N'KG', 300, 8, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Nuez de Castilla', N'Gran tamaño, secado al sol', 5.60, N'KG', 90, 8, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Almendra Tostada', N'Tostado lento con sal marina', 9.20, N'KG', 45, 8, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Pistacho Natural', N'Sabor original sin sal', 10.80, N'KG', 35, 8, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Tomate en Rama', N'Dulce y rojo intenso', 2.10, N'KG', 200, 9, 5, 2),
(NEXT VALUE FOR Seq_Productos, N'Lechuga Hoja de Roble', N'Color rojizo, textura suave', 1.35, N'Unidad', 80, 9, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Cebolla Morada', N'Ideal para decorar y ensaladas', 1.50, N'KG', 250, 9, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Ajo Violeta', N'Aroma persistente y medicinal', 4.40, N'KG', 110, 9, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Patata Agria', N'La mejor para freír patatas bravas', 1.10, N'KG', 800, 9, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Rábano Picante', N'Crujiente y con carácter', 1.10, N'Manojo', 100, 9, 11, 3),
(NEXT VALUE FOR Seq_Productos, N'Manzana Reineta', N'Textura arenosa para asar', 1.90, N'KG', 180, 9, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Pera Ercolina', N'Dulzura concentrada de invierno', 2.15, N'KG', 140, 9, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Mezcla Frutos Secos', N'Crudos y naturales', 8.50, N'KG', 60, 10, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Calabaza Butternut', N'Cremosa, ideal para purés', 1.40, N'KG', 180, 10, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Boniato Naranja', N'Rico en vitamina A', 1.80, N'KG', 150, 10, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Mandarina Tango', N'Sin pepitas y muy jugosa', 2.40, N'KG', 300, 10, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Kiwi Verde', N'Vitamina C directa de Madrid', 2.85, N'KG', 120, 10, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Plátano Maduro', N'Sabor canario en Madrid', 2.10, N'KG', 250, 10, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Berenjena Negra', N'Brillante y sin semillas', 2.20, N'KG', 80, 10, 16, 2),
(NEXT VALUE FOR Seq_Productos, N'Judía Verde Plana', N'Sin hilos, muy tierna al vapor', 3.60, N'KG', 90, 10, 15, 3),
(NEXT VALUE FOR Seq_Productos, N'Espárrago Triguero', N'Manojo de sabor silvestre', 3.50, N'Manojo', 70, 11, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Berenjena Blanca', N'Variedad tradicional suave', 2.60, N'KG', 50, 11, 16, 2),
(NEXT VALUE FOR Seq_Productos, N'Garbanzo Lechoso', N'Gran tamaño y piel finísima', 3.60, N'KG', 200, 11, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Dátiles Medjool', N'Textura de caramelo natural', 14.50, N'KG', 30, 11, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Manzana Story', N'Dulzura extrema y resistencia', 2.10, N'KG', 220, 11, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Pimiento Rojo', N'Carnoso y vibrante', 2.75, N'KG', 90, 11, 18, 2),
(NEXT VALUE FOR Seq_Productos, N'Nuez de Pecán', N'Sabor mantecoso único', 11.50, N'KG', 40, 11, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Tomate Cherry', N'Bocados dulces de huerto', 2.20, N'Bandeja', 100, 11, 5, 2),
(NEXT VALUE FOR Seq_Productos, N'Limón Verna', N'Piel fina y mucho zumo', 1.65, N'KG', 130, 12, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Calabacín Luna', N'Redondo para rellenar', 2.10, N'Unidad', 60, 12, 16, 2),
(NEXT VALUE FOR Seq_Productos, N'Puerro Grueso', N'Sabor profundo para guisos', 1.70, N'Manojo', 85, 12, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Lenteja Roja', N'Pelada, ideal para cremas', 2.90, N'KG', 160, 12, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Cebolleta Tierna', N'Manojo para ensaladas frescas', 1.25, N'Manojo', 90, 12, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Pera Ercolina', N'Textura suave y jugosa', 2.05, N'KG', 110, 12, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Almendra Cruda', N'Sin sal ni tostado, natural', 8.50, N'KG', 55, 12, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Seta de Cardo', N'Frescura de montaña', 8.80, N'KG', 45, 12, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Tomate Cherry Rama', N'Racimos frescos y dulces', 2.15, N'Bandeja', 110, 13, 5, 2),
(NEXT VALUE FOR Seq_Productos, N'Brócoli Morado', N'Variedad rústica de invierno', 2.25, N'Unidad', 50, 13, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Alubia Canela', N'Mantecosa de piel fina', 4.10, N'KG', 130, 13, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Patata Monalisa', N'La más versátil en la cocina', 1.10, N'KG', 700, 13, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Ajo Violeta Intenso', N'Sabor persistente', 4.35, N'KG', 120, 13, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Naranja Navelate', N'La reina de las naranjas de mesa', 1.65, N'KG', 350, 13, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Pistacho con Cáscara', N'Tostado artesanalmente', 10.90, N'KG', 55, 13, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Escarola', N'Ideal para ensaladas amargas', 1.50, N'Unidad', 65, 13, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Judía Boby', N'Redonda, tierna y sin hilos', 3.70, N'KG', 95, 14, 15, 3),
(NEXT VALUE FOR Seq_Productos, N'Col de Bruselas', N'Pequeñas y muy compactas', 2.95, N'KG', 70, 14, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Cebolla Chalota', N'Sabor delicado para chefs', 4.60, N'KG', 45, 14, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Habas Secas', N'Para guisos tradicionales madrileños', 2.75, N'KG', 140, 14, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Mandarina Gold Nugget', N'Dulzura extrema garantizada', 2.90, N'KG', 210, 14, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Orejones Albaricoque', N'Secado natural al sol', 9.80, N'KG', 45, 14, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Mezcla Cocktail', N'Frutos secos variados tostados', 8.20, N'KG', 75, 14, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Apio Blanco', N'Tallo tierno para picar o caldo', 1.30, N'Manojo', 60, 14, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Pack Sopa de Invierno', N'Puerro, zanahoria y chirivía frescos', 2.65, N'Unidad', 75, 15, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Nabo de Mesa', N'Tierno e ideal para el puchero', 0.95, N'KG', 130, 15, 11, 3),
(NEXT VALUE FOR Seq_Productos, N'Chirivía Fresca', N'Raíz aromática de temporada', 2.05, N'KG', 65, 15, 11, 3),
(NEXT VALUE FOR Seq_Productos, N'Cebolla Dulce', N'Sabor suave para ensalada', 1.45, N'KG', 310, 15, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Lenteja Beluga', N'Lenteja negra, caviar vegetal', 3.90, N'KG', 110, 15, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Manzana Ambrosía', N'Aroma a miel muy intenso', 2.30, N'KG', 190, 15, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Castaña Pilonga', N'Castaña seca ya pelada', 12.50, N'KG', 35, 15, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Rúcula', N'Bolsa 150g sabor picante', 1.55, N'Unidad', 50, 15, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Escarola Rizada', N'Corazón blanco, muy crujiente', 1.70, N'Unidad', 55, 16, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Apio Nabo', N'Para purés gourmet de invierno', 2.20, N'KG', 45, 16, 11, 3),
(NEXT VALUE FOR Seq_Productos, N'Patata Baby', N'Especial para guarnición asada', 1.95, N'KG', 210, 16, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Boniato Blanco', N'Menos dulce, textura más firme', 2.00, N'KG', 110, 16, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Pomelo Star Ruby', N'Rojo intenso y amargo dulce', 2.05, N'KG', 130, 16, 2, 1),
(NEXT VALUE FOR Seq_Productos, N'Higo Paso', N'Energía natural de la zona', 8.20, N'KG', 55, 16, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Lechuga Romana', N'Clásica y muy fresca', 1.10, N'Unidad', 100, 16, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Tomate Cherry', N'Bocados de dulzor', 2.25, N'KG', 80, 16, 5, 2),
(NEXT VALUE FOR Seq_Productos, N'Col de Milán', N'Hoja rizada especial para olla', 1.50, N'Unidad', 85, 17, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Saco Patata 5kg', N'Variedad Kennebec ahorro', 4.65, N'Unidad', 110, 17, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Garbanzo de la Vega', N'Cosecha local inmejorable', 2.75, N'KG', 420, 17, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Limón Mano de Buda', N'Aromático exclusivo para cocina', 8.50, N'Unidad', 15, 17, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Almendra Largueta', N'Almendra alargada crujiente', 4.35, N'KG', 220, 17, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Acelga Roja', N'Color y sabor intenso en rama', 1.40, N'Manojo', 55, 17, 7, 2),
(NEXT VALUE FOR Seq_Productos, N'Radicchio', N'Chicoria roja italiana amarga', 2.00, N'Unidad', 35, 17, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Hinojo', N'Sabor anisado para ensalada', 2.10, N'Unidad', 40, 17, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Cebolla Roja', N'Color intenso para ensaladas', 1.45, N'KG', 270, 18, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Patata para Freír', N'Saco 2kg variedad especial', 2.25, N'Unidad', 160, 18, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Naranja Sanguina', N'Pulpa color sangre antioxidante', 2.25, N'KG', 130, 18, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Nuez de Castilla', N'Gran tamaño, recién secada', 5.70, N'KG', 110, 18, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Pimiento Italiano', N'Verde, ideal para freír o guiso', 2.10, N'KG', 100, 18, 18, 2),
(NEXT VALUE FOR Seq_Productos, N'Espinaca', N'Manojo tierno de hoja verde', 1.35, N'Manojo', 60, 18, 7, 2),
(NEXT VALUE FOR Seq_Productos, N'Manzana Golden', N'Dulce y crujiente para niños', 1.50, N'KG', 200, 18, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Ajo', N'Cabeza de ajo blanco tradicional', 1.60, N'Unidad', 150, 18, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Colinabo', N'Cruce entre nabo y col, muy dulce', 1.85, N'KG', 65, 19, 11, 3),
(NEXT VALUE FOR Seq_Productos, N'Perejil Fresco', N'Manojo aromático indispensable', 0.70, N'Manojo', 110, 19, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Pasta de Ajo', N'Mortero artesano 100g listo', 3.75, N'Unidad', 55, 19, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Mandarina Tango', N'Sin pepitas, jugo equilibrado', 2.50, N'KG', 320, 19, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Pasas de Corinto', N'Pequeñas, dulces y potentes', 6.20, N'KG', 45, 19, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Calabaza Butternut', N'Cáscara fina y carne dulce', 1.45, N'KG', 160, 19, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Patata Kennebec', N'Todoterreno recién sacada', 1.15, N'KG', 500, 19, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Tomate de Ensalada', N'Variedad Roma muy firme', 1.80, N'KG', 100, 19, 5, 2),
(NEXT VALUE FOR Seq_Productos, N'Bimi', N'Brocoli baby dulce de invierno', 2.40, N'Manojo', 60, 20, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Tomate Kumato', N'Sabor dulce intenso y oscuro', 3.10, N'KG', 85, 20, 5, 2),
(NEXT VALUE FOR Seq_Productos, N'Lenteja de la Armuña', N'Legumbre con IGP, calidad extra', 3.35, N'KG', 160, 20, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Naranja Amarga', N'Especial para mermeladas caseras', 1.55, N'KG', 110, 20, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Cacahuete Tostado', N'Con cáscara y un toque de sal', 4.30, N'KG', 110, 20, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Espinaca Baby', N'Hoja tierna ideal para crudo', 1.65, N'Unidad', 70, 20, 7, 2),
(NEXT VALUE FOR Seq_Productos, N'Acelga Blanca', N'Tallo ancho y hoja suave', 1.20, N'Manojo', 90, 20, 7, 2),
(NEXT VALUE FOR Seq_Productos, N'Puerros Finos', N'Manojo para sofritos rápidos', 1.40, N'Manojo', 100, 20, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Calçots de Madrid', N'Manojo 25 unidades para asar', 9.80, N'Manojo', 130, 21, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Alcachofa Prat', N'Tierna y carnosa, cultivada aquí', 3.10, N'KG', 190, 21, 17, 2),
(NEXT VALUE FOR Seq_Productos, N'Tomate Montserrat', N'Forma de rosa, aromático', 3.30, N'KG', 95, 21, 5, 2),
(NEXT VALUE FOR Seq_Productos, N'Escarola Xató', N'Especial ensaladas de invierno', 1.70, N'Unidad', 75, 21, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Patata del Bufet', N'Variedad muy cremosa y fina', 1.75, N'KG', 520, 21, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Garbanzo de l''Anoia', N'Pequeño y suave en boca', 3.50, N'KG', 260, 21, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Manzana de Montaña', N'Dulce y de carne firme', 1.85, N'KG', 310, 21, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Avellana Tostada', N'Recién tostada en la finca', 7.80, N'KG', 65, 21, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Judía del Ganxet', N'Textura de seda inigualable', 5.80, N'KG', 115, 22, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Cebolla Figueres', N'Suave, rosada y muy dulce', 1.45, N'KG', 410, 22, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Naranja Navel', N'Mucha fibra y zumo dulce', 1.55, N'KG', 560, 22, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Limón de Finca', N'Cosechado sin ceras industriales', 1.70, N'KG', 160, 22, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Berenjena Blanca', N'Variedad tradicional recuperada', 2.45, N'KG', 75, 22, 16, 2),
(NEXT VALUE FOR Seq_Productos, N'Calabaza de Violín', N'Carne compacta naranja intenso', 1.35, N'KG', 140, 22, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Acelga Roja de Campo', N'Sabor rústico de invierno', 1.45, N'Manojo', 90, 22, 7, 2),
(NEXT VALUE FOR Seq_Productos, N'Ajo de Verdeo', N'Ajos tiernos para revueltos', 1.40, N'Manojo', 80, 22, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Brócoli Verde', N'Ramilletes compactos y frescos', 1.65, N'Unidad', 105, 23, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Espinaca de Invierno', N'Ideal para saltear con piñones', 1.45, N'Manojo', 75, 23, 7, 2),
(NEXT VALUE FOR Seq_Productos, N'Patata Roja del Pirineu', N'Resistente a la cocción larga', 1.30, N'KG', 620, 23, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Ajo Tierno', N'Manojo de sabor suave', 1.90, N'Manojo', 55, 23, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Kiwi del Maresme', N'Vitamina C madurada al sol', 3.00, N'KG', 190, 23, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Manzana Fuji', N'Crujiente y muy aromática', 2.10, N'KG', 320, 23, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Almendra con Sal', N'Tostado natural madrileño', 8.50, N'KG', 50, 23, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Pistacho Tostado', N'Con sal marina fina', 11.30, N'KG', 45, 23, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Habas Tiernas', N'Dulzura en vaina pequeña', 3.90, N'KG', 100, 24, 15, 3),
(NEXT VALUE FOR Seq_Productos, N'Puerro de Huerto', N'Limpio y blanco para purés', 1.65, N'Manojo', 120, 24, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Mandarina', N'Gajos dulces sin pepitas', 1.85, N'KG', 460, 24, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Lenteja de l''Alta Segarra', N'Sabor artesano tradicional', 2.95, N'KG', 360, 24, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Champiñón París', N'Entero para plancha o guiso', 3.60, N'KG', 130, 24, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Calabacín Fino', N'Muy digerible, piel suave', 1.95, N'KG', 170, 24, 16, 2),
(NEXT VALUE FOR Seq_Productos, N'Lechuga Romana', N'Corazón crujiente recién cortado', 1.20, N'Unidad', 110, 24, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Remolacha con Rama', N'Frescura garantizada de huerto', 1.40, N'Manojo', 70, 24, 11, 3),
(NEXT VALUE FOR Seq_Productos, N'Coliflor Blanca', N'Pieza firme y muy sabrosa', 1.95, N'Unidad', 65, 25, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Zanahoria Dulce', N'Manojo con rama recién sacada', 1.35, N'Manojo', 130, 25, 11, 3),
(NEXT VALUE FOR Seq_Productos, N'Patata Nueva', N'Piel fina y delicada de invierno', 1.50, N'KG', 720, 25, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Ajo Negro Artesano', N'Sabor dulce y fermentado', 18.50, N'KG', 25, 25, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Naranja Navelate', N'Naranja premium de mesa dulce', 1.70, N'KG', 520, 25, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Plátano de Canarias', N'Madurado de forma natural', 2.25, N'KG', 260, 25, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Nuez Extra', N'Recién pelada a mano artesanalmente', 9.80, N'KG', 45, 25, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Calabaza de Asar', N'Muy dulce para cremas o asados', 1.40, N'KG', 160, 25, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Judía Verde Perona', N'Ancha y plana, extra tierna', 3.50, N'KG', 110, 26, 15, 3),
(NEXT VALUE FOR Seq_Productos, N'Pepino Mediterráneo', N'Sabor suave y refrescante', 1.75, N'KG', 150, 26, 16, 2),
(NEXT VALUE FOR Seq_Productos, N'Boniato Dulce', N'Ideal para asar entero al horno', 1.85, N'KG', 230, 26, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Garbanzo de Valseca', N'Gran tamaño y ternura seda', 3.40, N'KG', 290, 26, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Pistacho Tostado', N'Crujiente y muy saludable', 11.50, N'KG', 55, 26, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Manzana Reineta', N'Ideal para compotas y asar', 2.00, N'KG', 240, 26, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Dátiles Medjool', N'Selección premium natural', 14.80, N'KG', 35, 26, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Nuez con Cáscara', N'Secado tradicional de sierra', 5.10, N'KG', 120, 26, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Escarola de Invierno', N'Corazón blanco y muy tierno', 1.65, N'Unidad', 75, 27, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Coliflor Sevillana', N'Firme y muy blanca, gran tamaño', 1.95, N'Unidad', 65, 27, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Patata Nueva', N'Piel muy fina, recién arrancada', 1.45, N'KG', 710, 27, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Naranja Sanguina', N'Pulpa color rojo antioxidante', 2.20, N'KG', 160, 27, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Nuez de Daganzo', N'Cosecha propia de la campiña', 5.60, N'KG', 90, 27, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Ajo de Verdeo', N'Ideal para tortillas de ajos tiernos', 1.45, N'Manojo', 60, 27, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Calabaza Luna', N'Redonda, especial para rellenar', 2.25, N'Unidad', 50, 27, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Chirivía Fresca', N'Aroma dulce e indispensable para caldo', 2.10, N'KG', 70, 27, 11, 3),
(NEXT VALUE FOR Seq_Productos, N'Boniato Dulce Naranja', N'Especial para hornear con canela', 1.85, N'KG', 230, 28, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Pera Ercolina', N'Pequeña, dulce y muy aromática', 2.10, N'KG', 160, 28, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Dátiles Naturales', N'Sin azúcares añadidos, energía pura', 13.00, N'KG', 35, 28, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Habas Tiernas Campiña', N'Vaina pequeña y muy dulce', 4.10, N'KG', 90, 28, 15, 3),
(NEXT VALUE FOR Seq_Productos, N'Rábano Largo Rojo', N'Picante y muy crujiente', 1.00, N'Manojo', 110, 28, 11, 3),
(NEXT VALUE FOR Seq_Productos, N'Lenteja Beluga', N'La lenteja gourmet de Madrid', 4.00, N'KG', 130, 28, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Champiñón Blanco', N'Frescura garantizada del día', 3.60, N'KG', 100, 28, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Espinaca de Invierno', N'Hoja rústica con mucho sabor', 1.50, N'Manojo', 80, 28, 7, 2),
(NEXT VALUE FOR Seq_Productos, N'Champiñón París Blanco', N'Fresco y firme, ideal para plancha', 3.50, N'KG', 100, 29, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Setas de Cardo Cultivo', N'Sabor delicado y textura carnosa', 8.20, N'KG', 40, 29, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Puerro de Colmenar', N'Tallo blanco y muy tierno', 1.55, N'Manojo', 90, 29, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Apio nabo', N'Raíz aromática para purés gourmet', 2.30, N'KG', 50, 29, 11, 3),
(NEXT VALUE FOR Seq_Productos, N'Espárrago Blanco Grueso', N'Calidad extra, muy tierno', 4.80, N'Manojo', 30, 29, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Castaña Pilonga', N'Castaña seca ya pelada artesanal', 12.00, N'KG', 45, 29, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Nuez de la Sierra', N'Recién recolectada y secada', 5.60, N'KG', 100, 29, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Patata Vitelotte', N'Patata morada de piel oscura', 2.85, N'KG', 60, 29, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Kiwi Verde Madrid', N'Alto en vitamina C, maduro natural', 2.95, N'KG', 180, 30, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Plátano de Invernadero', N'Sabor dulce y maduración lenta', 1.95, N'KG', 250, 30, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Piña Baby Gourmet', N'Dulce y aromática, pieza pequeña', 3.50, N'Unidad', 40, 30, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Col de Bruselas', N'Pequeñas, compactas y frescas', 2.90, N'KG', 70, 30, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Lombarda de Madrid', N'Color intenso, ideal para Navidad', 1.60, N'Unidad', 80, 30, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Boniato Blanco rústico', N'Menos dulce, textura muy firme', 1.90, N'KG', 120, 30, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Pistacho Tostado Sur', N'Con un toque de sal marina', 11.20, N'KG', 50, 30, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Dátil Medjool Extra', N'Carne jugosa y selección premium', 14.50, N'KG', 30, 30, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Tomate Kumato', N'Tomate oscuro de sabor intenso', 2.90, N'KG', 100, 31, 5, 2),
(NEXT VALUE FOR Seq_Productos, N'Rúcula en Bolsa', N'Hojas frescas de sabor picante', 1.45, N'Unidad', 60, 31, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Cebolla Chalota', N'Sabor delicado para cocina francesa', 4.50, N'KG', 40, 31, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Alubia Canela', N'Legumbre mantecosa de piel fina', 3.95, N'KG', 120, 31, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Naranja Navelate', N'Dulzura máxima de mesa', 1.65, N'KG', 400, 31, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Pomelo Star Ruby', N'Rojo intenso y muy saludable', 1.95, N'KG', 120, 31, 2, 1),
(NEXT VALUE FOR Seq_Productos, N'Anacardo Natural', N'Sin sal, ideal para snacks', 12.00, N'KG', 35, 31, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Seta Pleurotus', N'Seta de ostra muy fresca', 7.50, N'KG', 50, 31, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Aguacate Hass', N'Textura cremosa, origen local', 4.80, N'KG', 90, 32, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Granada Mollar', N'Grano dulce y blando', 2.30, N'KG', 150, 32, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Setas de Cultivo', N'Variedad mixta de la zona', 8.50, N'KG', 40, 32, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Pasa de Corinto', N'Sin semilla, dulzor concentrado', 6.20, N'KG', 60, 32, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Hinojo Fresco', N'Sabor anisado para ensaladas', 1.95, N'Unidad', 45, 33, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Ajo Negro Fermentado', N'Sabor dulce y saludable', 16.00, N'KG', 20, 33, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Chirimoya de Madrid', N'Sabor tropical en invernadero', 3.90, N'KG', 50, 33, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Orejones de Albaricoque', N'Secado natural al sol', 9.50, N'KG', 40, 33, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Níscalo de Madrid', N'Seta silvestre de temporada', 12.50, N'KG', 15, 34, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Mango Local', N'Producción limitada dulce', 4.50, N'KG', 30, 34, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Piñones Nacionales', N'Calidad suprema recién pelados', 32.00, N'KG', 10, 34, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Garbanzo de la Vega', N'Cosecha local muy tierna', 2.70, N'KG', 300, 34, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Chirivía de Invierno', N'Raíz aromática para caldos potentes', 2.10, N'KG', 60, 35, 11, 3),
(NEXT VALUE FOR Seq_Productos, N'Nabo de Mesa Blanco', N'Tierno y suave al paladar', 0.95, N'KG', 120, 35, 11, 3),
(NEXT VALUE FOR Seq_Productos, N'Setas de Cardo', N'Textura carnosa y sabor a monte', 8.50, N'KG', 40, 35, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Puerro de Verdeo', N'Manojo fresco de tallo blanco', 1.60, N'Manojo', 90, 35, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Patata Roja Saco 5kg', N'Variedad de piel roja para cocer', 4.90, N'Unidad', 50, 35, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Nuez con Cáscara', N'Secado natural al aire de sierra', 5.20, N'KG', 100, 35, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Manzana Ambrosía', N'Dulzura extrema y aroma a miel', 2.25, N'KG', 150, 35, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Escarola Currada', N'Corazón blanco, ideal para ensaladas', 1.55, N'Unidad', 70, 35, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Ajo Negro Artesano', N'Fermentado natural, sabor regaliz', 16.50, N'KG', 20, 36, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Dátil Medjool Real', N'Selección premium muy jugosa', 14.20, N'KG', 30, 36, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Kiwi Verde Madrid', N'Alto en vitamina C, maduración natural', 2.90, N'KG', 120, 36, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Mandarina Tango', N'Sin semillas, muy fácil de pelar', 2.45, N'KG', 300, 36, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Cebolla Roja Gourmet', N'Color intenso para platos especiales', 1.45, N'KG', 180, 36, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Brócoli en Ramillete', N'Superalimento recién cortado', 1.70, N'Unidad', 90, 36, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Almendra Tostada con Sal', N'Aperitivo artesanal crujiente', 9.10, N'KG', 50, 36, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Pera Ercolina', N'Dulzura concentrada de invierno', 2.10, N'KG', 140, 36, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Piña Baby Gourmet', N'Sabor tropical dulce en miniatura', 3.60, N'Unidad', 45, 37, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Granada Mollar', N'Grano rojo y dulce de temporada', 2.35, N'KG', 150, 37, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Calabaza de Violín', N'Carne firme y muy dulce', 1.35, N'KG', 220, 37, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Acelga de Campo', N'Manojo de 500g extra tierno', 1.15, N'Manojo', 100, 37, 7, 2),
(NEXT VALUE FOR Seq_Productos, N'Garbanzo Blanco Extra', N'Mantecoso, ideal para puchero', 3.20, N'KG', 400, 37, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Pistacho Tostado Sur', N'Tostado lento en horno artesano', 11.50, N'KG', 55, 37, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Higo Paso Seco', N'Dulce natural concentrado', 7.80, N'KG', 60, 37, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Pepino Mediterráneo', N'Sabor suave y refrescante', 1.70, N'KG', 130, 37, 16, 2),
(NEXT VALUE FOR Seq_Productos, N'Calabacín Fino Blanco', N'Ideal para cremas suaves o plancha', 1.90, N'KG', 180, 38, 16, 2),
(NEXT VALUE FOR Seq_Productos, N'Berenjena Negra', N'Brillante, firme y sin semillas', 2.10, N'KG', 90, 38, 16, 2),
(NEXT VALUE FOR Seq_Productos, N'Pimiento Italiano Verde', N'Sabor suave para sofritos', 1.85, N'KG', 120, 38, 18, 2),
(NEXT VALUE FOR Seq_Productos, N'Judía Verde Plana', N'Vaina tierna sin hilos', 3.45, N'KG', 100, 38, 15, 3),
(NEXT VALUE FOR Seq_Productos, N'Mandarina Gold Nugget', N'Dulzura máxima, piel rugosa', 2.80, N'KG', 150, 38, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Pasa de Corinto', N'Sin semilla, ideal para postres', 6.20, N'KG', 40, 38, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Castaña del Tiétar', N'Cosecha de sierra para asar', 5.40, N'KG', 90, 38, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Ajo Violeta', N'Aroma intenso y medicinal', 4.30, N'KG', 80, 38, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Coliflor Blanca Gigante', N'Firme y muy blanca', 2.05, N'Unidad', 50, 39, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Lombarda de Invierno', N'Clásico madrileño, color vivo', 1.70, N'Unidad', 60, 39, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Rábano Picante', N'Crujiente y con mucho carácter', 1.05, N'Manojo', 110, 39, 11, 3),
(NEXT VALUE FOR Seq_Productos, N'Patata Monalisa', N'Todoterreno de la cocina', 1.05, N'KG', 500, 39, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Cebolla Blanca Dulce', N'No amarga, perfecta en crudo', 1.40, N'KG', 250, 39, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Manzana Reineta', N'Textura arenosa para asar', 1.95, N'KG', 200, 39, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Nuez Pelada Extra', N'Selección de grano pelado a mano', 9.80, N'KG', 30, 39, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Alcachofa Tierna', N'Calibre mediano extra sabroso', 3.10, N'KG', 110, 39, 17, 2),
(NEXT VALUE FOR Seq_Productos, N'Puerro Grueso de Caldo', N'Sabor profundo para guisos', 1.55, N'Manojo', 85, 40, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Ajo Blanco de Aceuchal', N'Aroma seco de gran calidad', 4.00, N'KG', 130, 40, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Cebolla Chalota', N'Pequeña y de sabor refinado', 4.70, N'KG', 35, 40, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Garbanzo Pedrosillano', N'Grano pequeño, máxima ternura', 3.15, N'KG', 320, 40, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Orejones Albaricoque', N'Secado natural sin aditivos', 9.60, N'KG', 50, 40, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Pomelo Star Ruby', N'Rojo intenso y saludable', 1.95, N'KG', 100, 40, 2, 1),
(NEXT VALUE FOR Seq_Productos, N'Setas Pleurotus', N'Seta de ostra blanca y fresca', 7.90, N'KG', 45, 40, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Lechuga Romana', N'Corazón crujiente del día', 1.15, N'Unidad', 120, 40, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Colinabo Rústico', N'Cruce entre col y nabo, sabor dulce', 1.85, N'KG', 65, 41, 11, 3),
(NEXT VALUE FOR Seq_Productos, N'Rábano Largo', N'Picante y crujiente para ensaladas', 1.10, N'Manojo', 100, 41, 11, 2),
(NEXT VALUE FOR Seq_Productos, N'Pera de Invierno', N'Carne blanca y compacta, muy dulce', 1.75, N'KG', 220, 41, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Lenteja Roja', N'Pelada, ideal para cremas rápidas', 2.80, N'KG', 180, 41, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Ajo Aceite Artesano', N'Pasta de ajo natural para cocinar', 3.60, N'Unidad', 50, 41, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Naranja Navelate', N'Naranja de mesa calidad extra', 1.65, N'KG', 350, 41, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Castaña Pilonga', N'Castaña seca ya pelada', 12.00, N'KG', 40, 41, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Espinaca Baby', N'Hoja tierna para ensalada', 1.55, N'Unidad', 60, 41, 7, 2),
(NEXT VALUE FOR Seq_Productos, N'Aguacate Hass', N'Textura cremosa de cultivo local', 4.70, N'KG', 80, 42, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Mango de Madrid', N'Cultivo protegido, sabor dulce', 4.40, N'KG', 40, 42, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Cebolla Chalota', N'Sabor refinado para salsas gourmet', 4.50, N'KG', 35, 42, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Calabacín Luna', N'Redondo, ideal para rellenar', 2.10, N'Unidad', 50, 42, 16, 2),
(NEXT VALUE FOR Seq_Productos, N'Patata Roja', N'Especial para cocidos y purés', 1.15, N'KG', 500, 42, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Mandarina Orri', N'Considerada la mejor mandarina', 2.60, N'KG', 200, 42, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Pistacho Natural', N'Sin sal ni tostado, puro sabor', 11.00, N'KG', 45, 42, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Puerro de Huerta', N'Blanco y largo, muy tierno', 1.50, N'Manojo', 100, 42, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Portobello Marrón', N'Seta de sabor intenso y rústico', 4.25, N'KG', 60, 43, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Champiñón Blanco', N'Fresco del día, calibre mediano', 3.45, N'KG', 120, 43, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Brócoli Morado', N'Variedad antigua con más antioxidantes', 2.20, N'Unidad', 40, 43, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Col de Bruselas', N'Pequeñas y compactas, extra frescas', 2.90, N'KG', 75, 43, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Garbanzo Gordo', N'Extra mantecoso, piel inapreciable', 3.10, N'KG', 250, 43, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Orejones de Albaricoque', N'Secado natural al sol', 9.50, N'KG', 40, 43, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Manzana Reineta', N'Textura arenosa para asar', 1.95, N'KG', 180, 43, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Cebolla Blanca Dulce', N'No amarga, perfecta en crudo', 1.35, N'KG', 300, 43, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Judía Verde Perona', N'Plana y sin hilos, muy tierna', 3.40, N'KG', 100, 44, 15, 3),
(NEXT VALUE FOR Seq_Productos, N'Habas de Verdeo', N'Vaina pequeña y grano dulce', 3.80, N'KG', 60, 44, 15, 3),
(NEXT VALUE FOR Seq_Productos, N'Piñón Nacional', N'Calidad suprema recién pelado', 32.00, N'KG', 12, 44, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Anacardo Tostado', N'Sin sal, procesado artesanalmente', 12.50, N'KG', 30, 44, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Boniato Blanco', N'Textura firme, menos dulce que el rojo', 1.90, N'KG', 110, 44, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Naranja Sanguina', N'Pulpa color sangre, sabor exótico', 2.20, N'KG', 130, 44, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Apio Blanco', N'Limpio y listo para caldos', 1.25, N'Manojo', 80, 44, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Tomate Cherry Rama', N'Dulzura concentrada en racimo', 2.10, N'Bandeja', 90, 44, 5, 2),
(NEXT VALUE FOR Seq_Productos, N'Kiwi Amarillo', N'Dulzura superior al verde', 3.60, N'KG', 80, 45, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Plátano Maduro', N'Sabor dulce natural intenso', 2.05, N'KG', 200, 45, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Pepino Holandés', N'Piel fina y muy digerible', 1.65, N'KG', 150, 45, 16, 2),
(NEXT VALUE FOR Seq_Productos, N'Berenjena Blanca', N'Variedad tradicional muy suave', 2.50, N'KG', 55, 45, 16, 2),
(NEXT VALUE FOR Seq_Productos, N'Ajo Negro', N'Fermentado natural, toque umami', 15.50, N'KG', 25, 45, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Lenteja Beluga', N'La joya negra de las legumbres', 4.00, N'KG', 120, 45, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Nuez Pelada', N'Selección de mitades extra', 9.90, N'KG', 45, 45, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Lechuga Batavia', N'Fresca, rizada y muy verde', 1.20, N'Unidad', 100, 45, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Granada Mollar de Madrid', N'Dulce, de grano blando y muy roja', 2.40, N'KG', 110, 46, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Dátil Medjool Natural', N'Carne muy jugosa, selección extra', 14.50, N'KG', 35, 46, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Higo Paso de la Sierra', N'Secado artesanal, muy energético', 7.90, N'KG', 60, 46, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Patata Vitelotte', N'Patata morada gourmet de carne firme', 2.80, N'KG', 45, 46, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Mandarina Clementina', N'Sin pepitas, ideal para meriendas', 1.80, N'KG', 300, 46, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Cebolla Dulce Blanca', N'Sabor suave, no pica nada', 1.35, N'KG', 250, 46, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Brócoli en Ramillete', N'Fresco y con corteza tierna', 1.65, N'Unidad', 100, 46, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Calabaza de Asar', N'Muy dulce, especial para horno', 1.20, N'KG', 180, 46, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Pimiento Morrón Rojo', N'Carnoso y dulce, especial para asar', 2.95, N'KG', 85, 47, 18, 2),
(NEXT VALUE FOR Seq_Productos, N'Almendra Marcona con Piel', N'La mejor calidad para repostería', 9.60, N'KG', 50, 47, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Nuez de Castilla', N'Grano lleno y sabor intenso', 5.40, N'KG', 120, 47, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Puerro de Verdeo', N'Manojo de 3 unidades para sofritos', 1.50, N'Manojo', 90, 47, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Lechuga Batavia Verde', N'Hoja rizada y muy refrescante', 1.15, N'Unidad', 110, 47, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Zanahoria con Rama', N'Dulce, recién sacada de la huerta', 1.25, N'Manojo', 130, 47, 11, 2),
(NEXT VALUE FOR Seq_Productos, N'Garbanzo Pedrosillano', N'Pequeño y muy mantecoso', 3.15, N'KG', 300, 47, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Manzana Story', N'Variedad roja, crujiente y dulce', 1.90, N'KG', 200, 47, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Setas Pleurotus Frescas', N'Seta de ostra blanca, sabor suave', 7.90, N'KG', 50, 48, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Espinaca de Invierno', N'Hoja rústica de gran tamaño', 1.30, N'Manojo', 85, 48, 7, 2),
(NEXT VALUE FOR Seq_Productos, N'Acelga Blanca de Campo', N'Tallo ancho y muy tierno', 1.10, N'Manojo', 100, 48, 7, 2),
(NEXT VALUE FOR Seq_Productos, N'Escarola de Corazón Blanco', N'Especial para ensaladas de invierno', 1.50, N'Unidad', 70, 48, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Ajo Morado de Cabeza', N'Aroma potente de larga duración', 4.20, N'KG', 140, 48, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Lenteja Pardina', N'Legumbre de secano de cocción rápida', 2.40, N'KG', 400, 48, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Pera Ercolina Jugosa', N'Dulzura natural concentrada', 1.95, N'KG', 160, 48, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Naranja Navelina', N'Sin pepitas, ideal para zumo', 1.45, N'KG', 450, 48, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Remolacha con Rama', N'Frescura garantizada, color vibrante', 1.35, N'Manojo', 85, 49, 11, 2),
(NEXT VALUE FOR Seq_Productos, N'Nabicol de Madrid', N'Raíz de invierno tradicional', 1.45, N'KG', 105, 49, 11, 3),
(NEXT VALUE FOR Seq_Productos, N'Boletus Seco', N'Aroma puro para risottos y salsas', 16.00, N'Bote', 20, 49, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Lenteja de la Armuña', N'Denominación de origen protegida', 3.30, N'KG', 140, 49, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Naranja Navelina', N'Sin pepitas, pulpa muy jugosa', 1.55, N'KG', 380, 49, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Mezcla Gourmet', N'Nueces, pasas y almendras seleccionadas', 14.80, N'KG', 25, 49, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Hinojo Fresco', N'Sabor anisado para ensalada o guiso', 1.90, N'Unidad', 50, 49, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Patata Agria Saco', N'Ideal para freír, formato 5kg', 4.50, N'Unidad', 100, 49, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Boniato Naranja Dulce', N'Carne cremosa, especial para horno', 1.70, N'KG', 200, 50, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Calabaza de Asar Gorda', N'Piezas seleccionadas muy dulces', 1.20, N'KG', 180, 50, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Puerro de Verdeo', N'Blanco y largo para cocina', 1.45, N'Manojo', 110, 50, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Ajo Morado de Chinchón', N'Sabor potente e intenso de Madrid', 4.30, N'KG', 150, 50, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Cebolla Blanca Saco 2kg', N'Formato ahorro, sabor muy suave', 2.80, N'Unidad', 80, 50, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Manzana Story Roja', N'Color brillante y sabor muy dulce', 1.95, N'KG', 200, 50, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Pistacho Tostado con Sal', N'Snack artesanal de la finca', 11.20, N'KG', 60, 50, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Espinaca de Hoja Ancha', N'Limpia y lista para saltear', 1.40, N'Manojo', 90, 50, 7, 2),
(NEXT VALUE FOR Seq_Productos, N'Tomate Rosa Gigante', N'Sabor de antes, piel muy fina', 3.20, N'KG', 70, 51, 5, 2),
(NEXT VALUE FOR Seq_Productos, N'Pepino Mediterráneo', N'Crujiente y muy refrescante', 1.65, N'KG', 120, 51, 16, 2),
(NEXT VALUE FOR Seq_Productos, N'Mandarina Clemenules', N'Miel en gajos sin pepitas', 1.85, N'KG', 300, 51, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Limón Verna Sin Cera', N'Zumo abundante y piel aromática', 1.60, N'KG', 140, 51, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Judía Verde Perona', N'Ancha y sin hilos, extra tierna', 3.50, N'KG', 90, 51, 15, 3),
(NEXT VALUE FOR Seq_Productos, N'Garbanzo de la Vega', N'Legumbre local de cocción rápida', 2.90, N'KG', 250, 51, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Nuez de Grano Pelada', N'Envasada al vacío para conservar frescor', 9.80, N'KG', 40, 51, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Lechuga Batavia', N'Fresca, rizada y muy verde', 1.15, N'Unidad', 100, 51, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Ajo Negro Premium', N'Sabor a regaliz, toque umami natural', 15.50, N'KG', 25, 52, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Dátil Medjool Extra', N'Natural, carne muy jugosa y dulce', 14.50, N'KG', 35, 52, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Remolacha con Hojas', N'Frescura total, ideal para ensaladas', 1.35, N'Manojo', 80, 52, 11, 2),
(NEXT VALUE FOR Seq_Productos, N'Rábano Picante', N'Muy crujiente para dar carácter', 1.05, N'Manojo', 100, 52, 11, 2),
(NEXT VALUE FOR Seq_Productos, N'Lenteja Beluga', N'La lenteja negra caviar de Madrid', 4.10, N'KG', 110, 52, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Pera Conferencia', N'Textura granulosa, muy dulce', 1.80, N'KG', 180, 52, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Almendra Marcona', N'La mejor calidad, recién pelada', 9.90, N'KG', 50, 52, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Brócoli en Ramillete', N'Piezas seleccionadas muy verdes', 1.75, N'Unidad', 120, 52, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Kiwi Amarillo Dulce', N'Dulzura superior, madurado en planta', 3.60, N'KG', 90, 53, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Granada Mollar', N'Dulce y de grano blando rojo', 2.30, N'KG', 140, 53, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Setas de Ostra Blancas', N'Textura suave, sabor delicado', 7.90, N'KG', 60, 53, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Apio Blanco Manojo', N'Limpio y listo para caldos', 1.25, N'Manojo', 80, 53, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Patata Vitelotte Morada', N'Exclusiva patata gourmet', 2.95, N'KG', 55, 53, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Anacardos Tostados', N'Procesados artesanalmente en finca', 12.80, N'KG', 30, 53, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Escarola de Corazón Blanco', N'Especial ensaladas de invierno', 1.55, N'Unidad', 75, 53, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Higo Paso Seco', N'Energía natural de la sierra', 7.60, N'KG', 50, 53, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Portobello Marrón', N'Seta de sabor intenso y rústico', 4.25, N'KG', 65, 54, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Champiñón París', N'Seleccionado, blanco y firme', 3.50, N'KG', 130, 54, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Habas de Verdeo', N'Vaina pequeña y grano muy dulce', 3.75, N'KG', 80, 54, 15, 3),
(NEXT VALUE FOR Seq_Productos, N'Alubia Blanca Mantecosa', N'Textura de seda garantizada', 3.80, N'KG', 140, 54, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Naranja Navelate', N'La mejor naranja de mesa', 1.70, N'KG', 400, 54, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Pistaxto Natural Crudo', N'Sabor original sin sal añadida', 10.90, N'KG', 40, 54, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Calabacín Fino', N'Ideal para plancha o cremas', 1.85, N'KG', 160, 54, 16, 2),
(NEXT VALUE FOR Seq_Productos, N'Ajo Violeta Intenso', N'Aroma persistente y medicinal', 4.35, N'KG', 110, 54, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Col de Milán Rizada', N'Hoja firme ideal para olla', 1.45, N'Unidad', 90, 55, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Col de Bruselas', N'Pequeñas, frescas y muy compactas', 2.95, N'KG', 70, 55, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Piñones Nacionales', N'Calidad suprema recién pelados', 34.00, N'KG', 15, 55, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Pasas Moscatel', N'Dulce concentrado sin pepita', 6.20, N'KG', 60, 55, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Zanahoria Morada', N'Sabor rústico y alto en hierro', 1.65, N'Manojo', 50, 55, 11, 2),
(NEXT VALUE FOR Seq_Productos, N'Patata Agria Saco 2kg', N'La mejor para freír patatas bravas', 2.20, N'Unidad', 150, 55, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Nuez de Pecán', N'Sabor suave y mantecoso', 11.20, N'KG', 35, 55, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Tomate Cherry Rama', N'Dulce bocado de huerto', 2.20, N'Bandeja', 100, 55, 5, 2),
(NEXT VALUE FOR Seq_Productos, N'Alcachofa Tierna', N'Calibre mediano extra sabroso', 3.15, N'KG', 120, 56, 17, 2),
(NEXT VALUE FOR Seq_Productos, N'Boniato Blanco', N'Menos dulce, textura muy firme', 1.95, N'KG', 130, 56, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Orejones Albaricoque', N'Secado natural al sol de Madrid', 9.80, N'KG', 45, 56, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Cebolla Roja Gourmet', N'Color intenso para ensaladas', 1.50, N'KG', 220, 56, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Pera de Invierno', N'Carne compacta muy dulce', 1.85, N'KG', 160, 56, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Acelga de Campo', N'Manojo fresco recién cortado', 1.15, N'Manojo', 110, 56, 7, 2),
(NEXT VALUE FOR Seq_Productos, N'Garbanzo Pedrosillano', N'Grano pequeño, máxima ternura', 3.10, N'KG', 300, 56, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Pimiento Rojo Morrón', N'Carnoso, ideal para asar', 2.85, N'KG', 90, 56, 18, 2),
(NEXT VALUE FOR Seq_Productos, N'Manzana Reineta', N'Textura arenosa para asar', 1.95, N'KG', 180, 57, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Lenteja Pardina', N'No necesita remojo prolongado', 2.45, N'KG', 400, 57, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Castaña del Tiétar', N'Cosecha de sierra para asar', 5.50, N'KG', 120, 57, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Ajo Blanco Cabeza', N'Aroma seco de gran calidad', 1.60, N'Unidad', 200, 57, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Lechuga Romana', N'Crujiente corazón del día', 1.10, N'Unidad', 120, 57, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Nabicol rústico', N'Raíz de invierno tradicional', 1.45, N'KG', 100, 57, 11, 2),
(NEXT VALUE FOR Seq_Productos, N'Kiwi Verde', N'Vitamina C madurada natural', 2.90, N'KG', 150, 57, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Pepino Holandés', N'Piel fina y muy digerible', 1.70, N'KG', 140, 57, 16, 2),
(NEXT VALUE FOR Seq_Productos, N'Judía Blanca Fina', N'Mantecosa de cosecha propia', 3.65, N'KG', 160, 58, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Almendra con Cáscara', N'Variedad largueta crujiente', 4.30, N'KG', 200, 58, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Pomelo Rosa', N'Sabor amargo y saludable', 1.90, N'KG', 110, 58, 2, 1),
(NEXT VALUE FOR Seq_Productos, N'Mandarina Orri', N'Sabor premium sin semillas', 2.65, N'KG', 180, 58, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Setas Pleurotus', N'Seta de ostra blanca fresca', 7.95, N'KG', 55, 58, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Calabaza de Violín', N'Carne compacta para repostería', 1.40, N'KG', 150, 58, 13, 3),
(NEXT VALUE FOR Seq_Productos, N'Nuez Pelada Extra', N'Selección de mitades perfectas', 9.90, N'KG', 50, 58, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Acelga Roja de Campo', N'Sabor rústico de invierno', 1.40, N'Manojo', 80, 58, 7, 2),
(NEXT VALUE FOR Seq_Productos, N'Tomate Kumato Negro', N'Dulzura superior y firmeza', 2.95, N'KG', 90, 59, 5, 2),
(NEXT VALUE FOR Seq_Productos, N'Patata Kennebec', N'Todoterreno recién sacada', 1.10, N'KG', 600, 59, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Pasta de Ajo Natural', N'Mortero artesano 100g listo', 3.70, N'Unidad', 60, 59, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Guisante Fresco', N'En vaina para desgranar', 4.80, N'KG', 60, 59, 15, 3),
(NEXT VALUE FOR Seq_Productos, N'Pasa de Corinto', N'Pequeña, dulce y sin semilla', 6.25, N'KG', 50, 59, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Cebolla Roja Gourmet', N'Ideal para decorar platos', 1.55, N'KG', 200, 59, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Hinojo Fresco', N'Aroma anisado para ensaladas', 2.10, N'Unidad', 50, 59, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Boletus Seco', N'Aroma puro para risottos', 16.00, N'Bote', 25, 59, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Kiwi Amarillo Seleccionado', N'Variedad premium muy dulce', 3.80, N'KG', 70, 60, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Piña Baby de Invernadero', N'Sabor tropical cultivado en Madrid', 3.70, N'Unidad', 40, 60, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Boletus Seco Laminado', N'Intenso aroma para arroces y pastas', 16.50, N'Bote', 25, 60, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Nuez de Pecán Pelada', N'Sabor suave y textura mantecosa', 11.80, N'KG', 30, 60, 21, 4),
(NEXT VALUE FOR Seq_Productos, N'Patata Vitelotte Morada', N'Color espectacular para tus platos', 2.90, N'KG', 50, 60, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Cebolla Chalota Francesa', N'Delicada y aromática', 4.60, N'KG', 40, 60, 9, 3),
(NEXT VALUE FOR Seq_Productos, N'Mandarina Tango', N'Sin pepitas, jugo equilibrado', 2.50, N'KG', 200, 60, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Ajo Negro de Autor', N'Textura de gelatina y sabor dulce', 15.80, N'KG', 20, 60, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Setas de Ostra', N'Frescas del día, ideales para plancha', 7.80, N'KG', 60, 61, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Champiñón Portobello', N'Sabor más rústico que el blanco', 4.30, N'KG', 70, 61, 20, 2),
(NEXT VALUE FOR Seq_Productos, N'Habas Mayo', N'Vaina tierna con grano pequeño', 3.95, N'KG', 90, 61, 15, 3),
(NEXT VALUE FOR Seq_Productos, N'Guisante de Verdeo', N'Dulce bocado de temporada', 4.70, N'KG', 50, 61, 15, 3),
(NEXT VALUE FOR Seq_Productos, N'Pistaxto Natural', N'Sin sal, recién recolectado', 10.95, N'KG', 45, 61, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Dátil con Almendra', N'Bombón natural artesano', 15.00, N'KG', 20, 61, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Apio Blanco', N'Tallo limpio y muy crujiente', 1.35, N'Manojo', 80, 61, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Manzana Ambrosía', N'Aroma dulce y carne firme', 2.30, N'KG', 180, 61, 3, 1),
(NEXT VALUE FOR Seq_Productos, N'Granada Mollar Extra', N'Grano dulce y muy rojo', 2.50, N'KG', 120, 62, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Aguacate Hass de Madrid', N'Madurado en el árbol con cuidado', 4.85, N'KG', 60, 62, 4, 1),
(NEXT VALUE FOR Seq_Productos, N'Lenteja Beluga', N'La joya negra de las legumbres', 4.15, N'KG', 100, 62, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Garbanzo Lechoso', N'Gran tamaño y piel inexistente', 3.50, N'KG', 200, 62, 14, 3),
(NEXT VALUE FOR Seq_Productos, N'Pasta de Ajo Natural', N'100% ajo sin conservantes', 3.80, N'Unidad', 50, 62, 10, 3),
(NEXT VALUE FOR Seq_Productos, N'Limón Verna', N'Zumo abundante, sin tratamientos', 1.65, N'KG', 150, 62, 1, 1),
(NEXT VALUE FOR Seq_Productos, N'Pasas Moscatel Corinto', N'Pequeñas y muy dulces', 6.40, N'KG', 50, 62, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Escarola de Invierno', N'Ideal para ensaladas con granada', 1.60, N'Unidad', 80, 62, 6, 2),
(NEXT VALUE FOR Seq_Productos, N'Bimi / Brocolini', N'Tallo dulce y tierno', 2.45, N'Manojo', 60, 63, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Col de Milán', N'Hoja rizada especial guisos', 1.50, N'Unidad', 90, 63, 8, 2),
(NEXT VALUE FOR Seq_Productos, N'Orejones de Albaricoque', N'Secado natural al sol', 9.80, N'KG', 40, 63, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Anacardo Tostado', N'Sin sal, tostado lento', 12.90, N'KG', 30, 63, 22, 4),
(NEXT VALUE FOR Seq_Productos, N'Zanahoria Morada rústica', N'Variedad antigua recuperada', 1.70, N'Manojo', 50, 63, 11, 2),
(NEXT VALUE FOR Seq_Productos, N'Patata Monalisa', N'La más versátil de la cocina', 1.15, N'KG', 600, 63, 12, 3),
(NEXT VALUE FOR Seq_Productos, N'Hinojo Fresco', N'Sabor anisado para pescados', 2.15, N'Unidad', 40, 63, 19, 2),
(NEXT VALUE FOR Seq_Productos, N'Naranja Navelate', N'Dulzura premium de mesa', 1.70, N'KG', 350, 63, 1, 1);

---------------------
--CARRITO PRODUCTOS--
---------------------
INSERT INTO CARRITO_ITEMS (ID_ITEM, CANTIDAD, ID_USUARIO, ID_PRODUCTO) VALUES 
(NEXT VALUE FOR Seq_Carrito, 1.0, 2, 1),
(NEXT VALUE FOR Seq_Carrito, 2.0, 2, 6),
(NEXT VALUE FOR Seq_Carrito, 1.0, 2, 14),
(NEXT VALUE FOR Seq_Carrito, 3.0, 3, 12),
(NEXT VALUE FOR Seq_Carrito, 1.0, 3, 18),
(NEXT VALUE FOR Seq_Carrito, 2.0, 3, 3),
(NEXT VALUE FOR Seq_Carrito, 1.0, 3, 10),
(NEXT VALUE FOR Seq_Carrito, 2.0, 7, 5),
(NEXT VALUE FOR Seq_Carrito, 1.0, 7, 20),
(NEXT VALUE FOR Seq_Carrito, 2.5, 7, 1),
(NEXT VALUE FOR Seq_Carrito, 1.0, 11, 22),
(NEXT VALUE FOR Seq_Carrito, 2.0, 11, 15),
(NEXT VALUE FOR Seq_Carrito, 1.0, 11, 4),
(NEXT VALUE FOR Seq_Carrito, 2.0, 11, 8);

-----------
--PEDIDOS--
-----------
INSERT INTO PEDIDOS (ID_PEDIDO, FECHA_PEDIDO, TOTAL, ESTADO, ID_USUARIO, ID_DIRECCION_ENTREGA) VALUES 
(NEXT VALUE FOR Seq_Pedidos, '2026-20-01 14:30:00', 10.45, N'ENTREGADO', 2, 11),
(NEXT VALUE FOR Seq_Pedidos, '2026-22-01 09:45:00', 10.35, N'ENTREGADO', 3, 1),
(NEXT VALUE FOR Seq_Pedidos, '2026-25-01 12:00:00', 20.70, N'ENTREGADO', 4, 2),
(NEXT VALUE FOR Seq_Pedidos, '2026-28-01 20:10:00', 20.45, N'ENTREGADO', 5, 3), 
(NEXT VALUE FOR Seq_Pedidos, '2026-30-01 16:40:00', 16.45, N'ENTREGADO', 6, 4),
(NEXT VALUE FOR Seq_Pedidos, '2026-01-02 11:20:00', 13.10, N'ENTREGADO', 7, 5),
(NEXT VALUE FOR Seq_Pedidos, '2026-02-02 14:55:00', 25.20, N'ENTREGADO', 8, 6),
(NEXT VALUE FOR Seq_Pedidos, '2026-03-02 08:30:00', 18.55, N'ENTREGADO', 9, 7),
(NEXT VALUE FOR Seq_Pedidos, '2026-05-02 17:15:00', 8.10,  N'ENTREGADO', 10, 8),
(NEXT VALUE FOR Seq_Pedidos, '2026-06-02 13:00:00', 18.90, N'ENTREGADO', 11, 15),
(NEXT VALUE FOR Seq_Pedidos, '2026-07-02 19:40:00', 14.00, N'ENTREGADO', 12, 19),
(NEXT VALUE FOR Seq_Pedidos, '2026-08-02 10:20:00', 14.40, N'ENTREGADO', 13, 17),
(NEXT VALUE FOR Seq_Pedidos, '2026-09-02 22:10:00', 27.80, N'ENTREGADO', 14, 13),
(NEXT VALUE FOR Seq_Pedidos, '2026-10-02 15:30:00', 25.60, N'ENTREGADO', 15, 23),
(NEXT VALUE FOR Seq_Pedidos, '2026-11-02 09:45:00', 13.20, N'ENTREGADO', 16, 21),
(NEXT VALUE FOR Seq_Pedidos, '2026-11-02 10:15:00', 21.20, N'EN CAMINO', 2, 12),
(NEXT VALUE FOR Seq_Pedidos, '2026-12-02 18:20:00', 10.10, N'EN CAMINO', 3, 1),
(NEXT VALUE FOR Seq_Pedidos, '2026-13-02 11:30:00', 14.00, N'PENDIENTE', 4, 2),
(NEXT VALUE FOR Seq_Pedidos, '2026-14-02 09:00:00', 18.85, N'PENDIENTE', 5, 3),
(NEXT VALUE FOR Seq_Pedidos, '2026-15-02 21:00:00', 20.05, N'PENDIENTE', 6, 4); 

--------------------
--DETALLES PEDIDOS--
--------------------
INSERT INTO DETALLE_PEDIDOS (ID_DETALLE, ID_PEDIDO, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO) VALUES 
(NEXT VALUE FOR Seq_DetallesPedido, 1, 1, 2, 2.95),
(NEXT VALUE FOR Seq_DetallesPedido, 1, 2, 1, 1.10),
(NEXT VALUE FOR Seq_DetallesPedido, 1, 12, 3, 1.15),
(NEXT VALUE FOR Seq_DetallesPedido, 2, 4, 1, 4.70),
(NEXT VALUE FOR Seq_DetallesPedido, 2, 6, 2, 1.35),
(NEXT VALUE FOR Seq_DetallesPedido, 2, 18, 1, 2.95),
(NEXT VALUE FOR Seq_DetallesPedido, 3, 14, 2, 3.10),
(NEXT VALUE FOR Seq_DetallesPedido, 3, 22, 1, 11.00),
(NEXT VALUE FOR Seq_DetallesPedido, 3, 3, 2, 1.75),
(NEXT VALUE FOR Seq_DetallesPedido, 4, 20, 1, 4.25),
(NEXT VALUE FOR Seq_DetallesPedido, 4, 21, 1, 12.00),
(NEXT VALUE FOR Seq_DetallesPedido, 4, 5, 2, 2.10),
(NEXT VALUE FOR Seq_DetallesPedido, 5, 10, 2, 4.20),
(NEXT VALUE FOR Seq_DetallesPedido, 5, 7, 2, 1.55),
(NEXT VALUE FOR Seq_DetallesPedido, 5, 1, 3, 1.65),
(NEXT VALUE FOR Seq_DetallesPedido, 6, 15, 2, 3.40),
(NEXT VALUE FOR Seq_DetallesPedido, 6, 11, 2, 1.35),
(NEXT VALUE FOR Seq_DetallesPedido, 6, 4, 1, 3.60),
(NEXT VALUE FOR Seq_DetallesPedido, 7, 22, 1, 32.00),
(NEXT VALUE FOR Seq_DetallesPedido, 7, 12, 5, 1.10),
(NEXT VALUE FOR Seq_DetallesPedido, 7, 16, 2, 1.85),
(NEXT VALUE FOR Seq_DetallesPedido, 8, 20, 1, 7.90),
(NEXT VALUE FOR Seq_DetallesPedido, 8, 14, 2, 2.40),
(NEXT VALUE FOR Seq_DetallesPedido, 8, 3, 3, 1.95),
(NEXT VALUE FOR Seq_DetallesPedido, 9, 13, 2, 1.70),
(NEXT VALUE FOR Seq_DetallesPedido, 9, 19, 2, 1.25),
(NEXT VALUE FOR Seq_DetallesPedido, 9, 5, 1, 2.20),
(NEXT VALUE FOR Seq_DetallesPedido, 10, 8, 2, 1.45),
(NEXT VALUE FOR Seq_DetallesPedido, 10, 22, 1, 9.80),
(NEXT VALUE FOR Seq_DetallesPedido, 10, 1, 4, 1.55),
(NEXT VALUE FOR Seq_DetallesPedido, 11, 17, 2, 3.15), 
(NEXT VALUE FOR Seq_DetallesPedido, 11, 6, 2, 1.10),
(NEXT VALUE FOR Seq_DetallesPedido, 11, 21, 1, 5.50),
(NEXT VALUE FOR Seq_DetallesPedido, 12, 10, 1, 3.70),
(NEXT VALUE FOR Seq_DetallesPedido, 12, 15, 1, 4.80),
(NEXT VALUE FOR Seq_DetallesPedido, 12, 12, 2, 2.95),
(NEXT VALUE FOR Seq_DetallesPedido, 13, 4, 1, 3.80), 
(NEXT VALUE FOR Seq_DetallesPedido, 13, 20, 1, 16.50),
(NEXT VALUE FOR Seq_DetallesPedido, 13, 1, 3, 2.50),
(NEXT VALUE FOR Seq_DetallesPedido, 14, 15, 2, 3.95),
(NEXT VALUE FOR Seq_DetallesPedido, 14, 22, 1, 15.00),
(NEXT VALUE FOR Seq_DetallesPedido, 14, 19, 2, 1.35),
(NEXT VALUE FOR Seq_DetallesPedido, 15, 14, 2, 4.15),
(NEXT VALUE FOR Seq_DetallesPedido, 15, 2, 2, 1.65),
(NEXT VALUE FOR Seq_DetallesPedido, 15, 6, 1, 1.60),
(NEXT VALUE FOR Seq_DetallesPedido, 16, 8, 2, 2.45), 
(NEXT VALUE FOR Seq_DetallesPedido, 16, 22, 1, 12.90), 
(NEXT VALUE FOR Seq_DetallesPedido, 16, 11, 2, 1.70),
(NEXT VALUE FOR Seq_DetallesPedido, 17, 5, 2, 3.00), 
(NEXT VALUE FOR Seq_DetallesPedido, 17, 6, 1, 1.30), 
(NEXT VALUE FOR Seq_DetallesPedido, 17, 13, 2, 1.40),
(NEXT VALUE FOR Seq_DetallesPedido, 18, 20, 1, 7.95), 
(NEXT VALUE FOR Seq_DetallesPedido, 18, 2, 2, 1.95), 
(NEXT VALUE FOR Seq_DetallesPedido, 18, 3, 1, 2.15),
(NEXT VALUE FOR Seq_DetallesPedido, 19, 10, 2, 4.30), 
(NEXT VALUE FOR Seq_DetallesPedido, 19, 18, 1, 2.95), 
(NEXT VALUE FOR Seq_DetallesPedido, 19, 14, 2, 3.65),
(NEXT VALUE FOR Seq_DetallesPedido, 20, 21, 1, 10.50), 
(NEXT VALUE FOR Seq_DetallesPedido, 20, 12, 3, 2.25), 
(NEXT VALUE FOR Seq_DetallesPedido, 20, 9, 2, 1.40);

---------
--PAGOS--
---------
INSERT INTO PAGOS (ID_PAGO, ID_PEDIDO, PASARELA, METODO_PAGO, ULTIMOS_DIGITOS_TARJETA, ESTADO_PAGO, STRIPE_SESSION_ID, FECHA_PAGO) VALUES 
(NEXT VALUE FOR Seq_Pagos, 1, 'STRIPE', 'TARJETA', '4521', 'COMPLETADO', 'cs_test_a1b2c3', '2026-20-01 14:30:00'),
(NEXT VALUE FOR Seq_Pagos, 2, 'PAYPAL', 'TARJETA', '8832', 'COMPLETADO', 'PAY-772155', '2026-22-01 09:45:00'),
(NEXT VALUE FOR Seq_Pagos, 3, 'STRIPE', 'TARJETA', '1004', 'COMPLETADO', 'cs_test_m5n6o7', '2026-25-01 12:00:00'),
(NEXT VALUE FOR Seq_Pagos, 4, 'REDSYS', 'TARJETA', '6650', 'COMPLETADO', 'AUTH_1122', '2026-28-01 20:10:00'),
(NEXT VALUE FOR Seq_Pagos, 5, 'PAYPAL', 'TARJETA', '3321', 'COMPLETADO', 'PAY-990011', '2026-30-01 16:40:00'),
(NEXT VALUE FOR Seq_Pagos, 6, 'STRIPE', 'TARJETA', '9982', 'COMPLETADO', 'cs_test_q1w2e3', '2026-01-02 11:20:00'),
(NEXT VALUE FOR Seq_Pagos, 7, 'REDSYS', 'TARJETA', '7711', 'COMPLETADO', 'AUTH_5566', '2026-02-02 14:55:00'),
(NEXT VALUE FOR Seq_Pagos, 8, 'PAYPAL', 'TARJETA', '2244', 'COMPLETADO', 'PAY-112233', '2026-03-02 08:30:00'),
(NEXT VALUE FOR Seq_Pagos, 9, 'STRIPE', 'TARJETA', '5567', 'COMPLETADO', 'cs_test_p0o9i8', '2026-05-02 17:15:00'),
(NEXT VALUE FOR Seq_Pagos, 10, 'REDSYS', 'TARJETA', '4433', 'COMPLETADO', 'AUTH_8899', '2026-06-02 13:00:00'),
(NEXT VALUE FOR Seq_Pagos, 11, 'PAYPAL', 'TARJETA', '1122', 'COMPLETADO', 'PAY-445566', '2026-07-02 19:40:00'),
(NEXT VALUE FOR Seq_Pagos, 12, 'STRIPE', 'TARJETA', '9001', 'COMPLETADO', 'cs_test_l5k4j3', '2026-08-02 10:20:00'),
(NEXT VALUE FOR Seq_Pagos, 13, 'REDSYS', 'TARJETA', '3344', 'COMPLETADO', 'AUTH_2233', '2026-09-02 22:10:00'),
(NEXT VALUE FOR Seq_Pagos, 14, 'PAYPAL', 'TARJETA', '6677', 'COMPLETADO', 'PAY-998877', '2026-10-02 15:30:00'),
(NEXT VALUE FOR Seq_Pagos, 15, 'STRIPE', 'TARJETA', '5544', 'COMPLETADO', 'cs_test_u1i2o3', '2026-11-02 09:45:00'),
(NEXT VALUE FOR Seq_Pagos, 16, 'REDSYS', 'TARJETA', '4521', 'COMPLETADO', 'AUTH_9921', '2026-11-02 10:15:00'),
(NEXT VALUE FOR Seq_Pagos, 17, 'STRIPE', 'TARJETA', '8832', 'COMPLETADO', 'cs_test_z9y8x7', '2026-12-02 18:20:00'),
(NEXT VALUE FOR Seq_Pagos, 18, 'PAYPAL', 'TARJETA', '1004', 'PENDIENTE', NULL, '2026-13-02 11:30:00'),
(NEXT VALUE FOR Seq_Pagos, 19, 'STRIPE', 'TARJETA', '6650', 'PENDIENTE', NULL, '2026-14-02 09:00:00'),
(NEXT VALUE FOR Seq_Pagos, 20, 'REDSYS', 'TARJETA', '3321', 'PENDIENTE', NULL, '2026-15-02 21:00:00');