-- CREACIÓN DE LA BASE DE DATOS
--CREATE DATABASE SAZON_LOCAL_DB;
--USE SAZON_LOCAL;

-- BORRAR SECUENCIAS
DROP SEQUENCE Seq_Roles;
DROP SEQUENCE Seq_Categorias;
DROP SEQUENCE Seq_Usuarios;
DROP SEQUENCE Seq_Direcciones;
DROP SEQUENCE Seq_Fincas;
DROP SEQUENCE Seq_Subcategorias;
DROP SEQUENCE Seq_Productos;
DROP SEQUENCE Seq_Carrito;
DROP SEQUENCE Seq_Pedidos;
DROP SEQUENCE Seq_DetallesPedido;
DROP SEQUENCE Seq_Pagos;

-- BORRAR TABLAS SI EXISTEN
DROP TABLE IF EXISTS PAGOS;
DROP TABLE IF EXISTS DETALLE_PEDIDOS;
DROP TABLE IF EXISTS PEDIDOS;
DROP TABLE IF EXISTS CARRITO_ITEMS;
DROP TABLE IF EXISTS PRODUCTOS;
DROP TABLE IF EXISTS SUBCATEGORIAS;
DROP TABLE IF EXISTS FINCAS;
DROP TABLE IF EXISTS DIRECCIONES;
DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS CATEGORIAS;
DROP TABLE IF EXISTS ROLES;

-- CREACION SECUENCIAS
CREATE SEQUENCE Seq_Roles START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Categorias START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Usuarios START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Direcciones START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Fincas START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Subcategorias START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Productos START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Carrito START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Pedidos START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_DetallesPedido START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE Seq_Pagos START WITH 1 INCREMENT BY 1;

-- CREACION TABLAS
CREATE TABLE ROLES (
    ID_ROL INT PRIMARY KEY,
    NOMBRE NVARCHAR(50) NOT NULL
);

CREATE TABLE CATEGORIAS (
    ID_CATEGORIA INT PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    DESCRIPCION NVARCHAR(255)
);

CREATE TABLE USUARIOS (
    ID_USUARIO INT PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    APELLIDOS NVARCHAR(255) NOT NULL,
    EMAIL NVARCHAR(100) UNIQUE NOT NULL,
    CONTRASENA NVARCHAR(255) NOT NULL,
    IMAGEN NVARCHAR(255),
    TELEFONO NVARCHAR(20),
    ID_ROL INT NOT NULL,
    CONSTRAINT FK_USUARIOS_ROLES FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL)
);

CREATE TABLE DIRECCIONES (
    ID_DIRECCION INT PRIMARY KEY,
    NOMBRE_ETIQUETA NVARCHAR(50), 
    CALLE_NUMERO NVARCHAR(255) NOT NULL,
    CODIGO_POSTAL NVARCHAR(10) NOT NULL,
    MUNICIPIO NVARCHAR(100) NOT NULL,
    PROVINCIA NVARCHAR(100) NOT NULL,
    LATITUD DECIMAL(10, 8),
    LONGITUD DECIMAL(11, 8),
    ES_PRINCIPAL BIT DEFAULT 0,
    ID_USUARIO INT NOT NULL,
    CONSTRAINT FK_DIRECCIONES_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE
);

CREATE TABLE FINCAS (
    ID_FINCA INT PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    DIRECCION NVARCHAR(255),
    MUNICIPIO NVARCHAR(100),
    PROVINCIA NVARCHAR(100),
    LATITUD DECIMAL(10, 8) NOT NULL,
    LONGITUD DECIMAL(10, 8) NOT NULL,
    ID_USUARIO INT NOT NULL, 
    CONSTRAINT FK_FINCAS_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE
);

CREATE TABLE SUBCATEGORIAS (
    ID_SUBCATEGORIA INT PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    DESCRIPCION NVARCHAR(255),
    IMAGEN NVARCHAR(100) NOT NULL,
    ID_CATEGORIA INT,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    DESCRIPCION NVARCHAR(MAX),
    IMAGEN NVARCHAR(255),
    PRECIO_UNIDAD DECIMAL(10, 2) NOT NULL,
    UNIDAD_MEDIDA NVARCHAR(20) DEFAULT N'KG',
    STOCK DECIMAL(10, 2) DEFAULT 0,
    ESTA_ACTIVO BIT DEFAULT 1,
    ID_FINCA INT NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    ID_SUBCATEGORIA INT NOT NULL,
    CONSTRAINT FK_PRODUCTOS_FINCAS FOREIGN KEY (ID_FINCA) REFERENCES FINCAS(ID_FINCA) ON DELETE CASCADE,
    CONSTRAINT FK_PRODUCTOS_SUBCATEGORIAS FOREIGN KEY (ID_SUBCATEGORIA) REFERENCES SUBCATEGORIAS(ID_SUBCATEGORIA),
    CONSTRAINT FK_PRODUCTOS_CATEGORIAS FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

CREATE TABLE CARRITO_ITEMS (
    ID_ITEM INT PRIMARY KEY,
    CANTIDAD DECIMAL(10, 2) NOT NULL DEFAULT 1,
    ID_USUARIO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CONSTRAINT FK_CARRITO_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK_CARRITO_PRODUCTOS FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO) ON DELETE NO ACTION
);

CREATE TABLE PEDIDOS (
    ID_PEDIDO INT PRIMARY KEY,
    FECHA_PEDIDO DATETIME DEFAULT GETDATE(),
    TOTAL DECIMAL(10, 2) NOT NULL,
    ESTADO NVARCHAR(50) DEFAULT N'PENDIENTE',
    ID_USUARIO INT NOT NULL,
    ID_DIRECCION_ENTREGA INT,
    CONSTRAINT FK_PEDIDOS_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_PEDIDOS_DIRECCIONES FOREIGN KEY (ID_DIRECCION_ENTREGA) REFERENCES DIRECCIONES(ID_DIRECCION)
);

CREATE TABLE DETALLE_PEDIDOS (
    ID_DETALLE INT PRIMARY KEY,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10, 2) NOT NULL,
    CONSTRAINT FK_DETALLE_PEDIDOS FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO) ON DELETE CASCADE,
    CONSTRAINT FK_DETALLE_PRODUCTOS FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE PAGOS (
    ID_PAGO INT PRIMARY KEY,
    ID_PEDIDO INT NOT NULL,
    PASARELA NVARCHAR(50) DEFAULT N'STRIPE',
    METODO_PAGO NVARCHAR(50) DEFAULT N'TARJETA',
    ULTIMOS_DIGITOS_TARJETA NVARCHAR(4),
    ESTADO_PAGO NVARCHAR(50), 
    STRIPE_SESSION_ID NVARCHAR(255),
    FECHA_PAGO DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_PAGOS_PEDIDOS FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);